### ISSUE TITLE
Soundfonts that use loop offsets rather than sample loop points do not loop.

### ISSUE THREAD

**Issue by DaforLynx** [FluidSynth/fluidsynth#1017]
### FluidSynth version
FluidSynth runtime version 2.2.4
Copyright (C) 2000-2021 Peter Hanappe and others.
Distributed under the LGPL license.
SoundFont(R) is a registered trademark of Creative Technology Ltd.

### Describe the bug
When playing samples with loop points set in the instrument's "loop start offset" and "loop end offset" (as described in Polyphone), with loop points set from 0 - 0 in the sample itself, the sample will not loop.

### Expected behavior
The sample should loop properly from the loop start offset to the loop end offset, if there is no loop points set in the sample itself. This is the case for other soundfont players including Musescore's, SynthFont's, and in Polyphone itself.

### Steps to reproduce

1. Download the sample MIDI file and sample SF2 file below.
2. Open a command window in the fluidsynth parent folder.
3. Type `./fluidsynth "DPPt.sf2" "Lake.mid"` with the appropriate file locations.

### Additional context
As stated before, this seems to be a common feature in most other soundfont players. Worth noting is that I used VGMTrans to create the soundfont.

When discovering this, I tested it with the loop points set in the sample itself rather than using offset values, and it worked perfectly. Try replacing the old soundfont with the "fixed" soundfont in which I changed the string sound to the working method. And for the record it'd be an extremely arduous process for me to go through every sample of every soundfont coming out of VGMTrans and change these values.

[Sample MIDI file](https://drive.google.com/file/d/13jvug2e3r4PhigXUTspFliryIXfmjwYk/view?usp=sharing)
[Sample SF2](https://drive.google.com/file/d/1z86EzZbKev9JUNDPLunY57H2PFU-XzVG/view?usp=sharing)
["Fixed" Sample SF2](https://drive.google.com/file/d/1w0Rxe9th68GHZYn1yBQNYuhjaVf7j7oq/view?usp=sharing)

![image](https://user-images.githubusercontent.com/13303368/148135816-e9db8394-e08f-4812-83a2-7dc134a115cd.png)

The method on the left does not work in fluidsynth, the method on the right does.

**Comment by derselbst** [comment]
Sample loops - we're now entering the gray zone of the SoundFont spec.

Technically, the SoundFont spec has various requirements to the sample loops. E.g. they must be at least 32 samples long, cf. Section 7.10 of the SF2.04 spec. There must even be padding around the sample loops and other fun to guarantee an artifact-free playback. Unfortunately, the spec makes no statement about how to deal with sample loops after they've been processed (clobbered) by the loop offset modulators. That's one of the reasons why FluidSynth ignores most of those sample-loop-requirements and even accepts completely broken loops, which have their loopstart before the actual start of the sample data. Similar for loopend.

But FluidSynth does one thing: If `loopstart == loopend`, it considers that loop to be _disabled at sample level_:

https://github.com/FluidSynth/fluidsynth/blob/015c6af52d8233eaae556242b5200290558ba415/src/sfloader/fluid_sfont.c#L789-L798

So, whereas previously `loopstart == loopend == sample->start`, now loopstart and loopend become zero. That means, they are pointing to the beginning of the smpl chunk.

Great. Now, once the loop offset modulators are running, we are reaching this code snippet:

https://github.com/FluidSynth/fluidsynth/blob/015c6af52d8233eaae556242b5200290558ba415/src/synth/fluid_voice.c#L1035-L1059

loopstart and loopend will now be set to their respective position, however FROM the beginning of the smpl chunk. And not, from the beginning of the sample (which would be the correct case).

Now loopstart and loopend are pointing to some data points at the beginning of the smpl chunk. Those data points are unlikely part of the belonging sample. Because of that, we are very likely to trigger this line:

https://github.com/FluidSynth/fluidsynth/blob/015c6af52d8233eaae556242b5200290558ba415/src/rvoice/fluid_rvoice.c#L186

and that line:

https://github.com/FluidSynth/fluidsynth/blob/015c6af52d8233eaae556242b5200290558ba415/src/rvoice/fluid_rvoice.c#L196

Now, `loopstart == loopend == sample->start`, which means, the loop is too short. Unlucky. And we're silently putting the sample to non-looped mode:

https://github.com/FluidSynth/fluidsynth/blob/015c6af52d8233eaae556242b5200290558ba415/src/rvoice/fluid_rvoice.c#L215

The easiest fix I can think of is #1018. Pls. have a try. In case it works well, I'm not quite sure if we can already take this for 2.2.5 or whether we postpone the fix to fluidsynth 2.3.0. The test effort could be quite tremendous. And I would probably need @mawe42's opinion on that.

**Comment by mawe42** [comment]
Ahh... yet another creative way to (ab)use the many holes in the SoundFont spec. :-)

Setting `loopstart = loopend = sample->start` as proposed in #1018 will probably work in this case. I've got a nagging feeling that we have some more checks like this in other places, though. But it's been quite a while since I look at that part of the codebase, so I might be mistaken.

As the spec is open to interpretation here, I would definitely vote to do what most other SF2 players do. But it would definitely be interesting to know how Polyphone, Muse and the others handle the case if the sample doesn't have 0 - 0 loop pointers, but 4000 - 4000, for example. If that works also as intended by the SF author, then maybe it's a sign that we still to too much loop validation and should even remove the check for loopstart = loopend.

**Comment by DaforLynx** [comment]
I've spent the past 3 hours trying to figure out how to compile this and I've found no success, so I'm not going to be able to test anytime soon. But if you test it with the linked files you should be able to see if it works.

**Comment by derselbst** [comment]
> I've spent the past 3 hours trying to figure out how to compile this and I've found no success

That's a strange statement. What's the error you came up with? Or have you spent 3 hours trying to understand [the documentation](https://github.com/FluidSynth/fluidsynth/wiki/BuildingWithCMake)? We also have various CI builds to make sure everything builds successfully. So, just stating "I spent hours" is hard to take serious.

> But if you test it with the linked files you should be able to see if it works.

I did that, ofc. And it sounds differently. But I cannot tell whether it sounds as intended.

**Comment by DaforLynx** [comment]
I'm wasn't entirely kidding about the "hours" part. It's nothing wrong with the compiler, or even necessarily this project specifically. It's just that there's so much stuff I have to find and download. I'm not a developer by trade or anything - have no experience with C or C++, if you would believe. The problem point was trying to install pkg-config by myself. It was surprisingly difficult for me to figure out how to compile it. Turns out I could just nick the binary from some repository somewhere. So I think I successfully did that, but now I'm getting weird unspecific errors when compiling fluidsynth. That's where I stopped, but I'll try again tomorrow. Sorry for being so negative.

**Comment by derselbst** [comment]
> It was surprisingly difficult for me to figure out how to compile it. 

Are you on Windows? In this case, you can just take one of the precompiled binaries:
https://dev.azure.com/tommbrt/tommbrt/_build/results?buildId=6740&view=artifacts&pathAsName=false&type=publishedArtifacts

**Comment by DaforLynx** [comment]
> > It was surprisingly difficult for me to figure out how to compile it.
> 
> Are you on Windows? In this case, you can just take one of the precompiled binaries: https://dev.azure.com/tommbrt/tommbrt/_build/results?buildId=6740&view=artifacts&pathAsName=false&type=publishedArtifacts

That, ah, makes things significantly easier. I just assumed compilations were automatically deleted after CI.

**Comment by DaforLynx** [comment]
> But I cannot tell whether it sounds as intended.

I can confirm it is sounding as intended. And somehow it sounds even better/more accurate than either Musescore or SynthFont (Musescore by a long shot - that program does strange things with the looping in these soundfonts). It did do something weird with pitch bends in one of my MIDI files but that's not relevant. Do you need me to test anything else with this change?

**Comment by DaforLynx** [comment]
Example. This is 100% how it should sound. It also works with all of the other soundfonts I used VGMTrans to rip (I just realized it might not be VGMTrans that is doing the loop offset thing, but rather the Synthfont feature that converts DLS to SF2). 

https://user-images.githubusercontent.com/13303368/148440948-fd8c98b8-f1cc-45fa-bc70-c1eada7dcf42.mp4

**Comment by derselbst** [comment]
> Do you need me to test anything else with this change?

Ok, thanks for the report and for confirming. That's it for you. I will discuss the technical details with Marcus in #1018 during the next days / weeks.

**Comment by sykhro** [comment]
> Worth noting is that I used VGMTrans to create the soundfont

Out of curiosity, are you using an old version? We use fluidsynth for playback in VGMTrans nowadays, via SF2.

**Comment by DaforLynx** [comment]
> Out of curiosity, are you using an old version? We use fluidsynth for playback in VGMTrans nowadays, via SF2.

Possibly. I couldn't find the version but the folder is labelled 9_29_09. Not sure if I even got it from GitHub. I don't think that would matter, though, because I used VGMTrans to export the DLS, which I then converted to SF2 with Synthfont. Sorry for the confusion.
