### ISSUE TITLE
fluid_synth_noteoff() return value

### ISSUE THREAD

**Issue by NANDLAB** [FluidSynth/fluidsynth#1036]
### Discussed in https://github.com/FluidSynth/fluidsynth/discussions/1034

<div type='discussions-op-text'>

<sup>Originally posted by **NANDLAB** January 16, 2022</sup>
Hello everyone,

in the documentation it says about the fluid_synth_noteoff() return value:

> FLUID_OK on success, FLUID_FAILED otherwise (may just mean that no voices matched the note off event)

Now, is there a way to distinguish between "no voices matched the note off event" and an actual error?

I am writing a C++ wrapper around fluidsynth and I am always checking the return codes of the libfluidsynth functions. If it is FLUID_FAILED (-1), I am throwing an exception.

```cpp
void fluid_synth_auto::noteoff(int chan, int key) const {
    if (fluid_synth_noteoff(ptr, chan, key)) {
        throw fluid_exception();
    }
}
```

In my program, if a note faded out after a note_on, and I call noteoff, it throws an exception, which is unexpected.

How do I handle the return value of noteoff correctly?</div>

Can you please make the return value of fluid_synth_noteoff() more detailed, to distinguish between "no matching voice" and a real error? E.g. FLUID_OK, FLUID_NO_VOICE_MATCH and FLUID_FAILED.

**Comment by derselbst** [comment]
I understand that you want to throw an exception if the function fails due to an error. But what would you do if the function returns either FLUID_OK or FLUID_NO_VOICE_MATCH? Changing the return value would be an API breaking change. Quite heavy - so really need to give some more details  / justification for such a change.

**Comment by derselbst** [comment]
The return value `FLUID_NO_VOICE_MATCH` of `fluid_synth_noteoff()` you're asking for would be only meaningful, when called from within synth-context. When called from outside synth-context, the return value highly depends on whether the call was made a few milliseconds sooner or later. That's why I'm closing this now.
