### ISSUE TITLE
Mobile XMF & Mobile DLS support

### ISSUE THREAD

**Issue by nehochupechatat** [FluidSynth/fluidsynth#1044]
FluidSynth already has DLS support, so it would be nice to add mobile DLS support.
Mobile DLS is a lot like regular DLS but with GM2 mapping and with the ability to use sample compression such as IMA ADPCM, a-law, u-law, etc
https://www.midi.org/specifications-old/item/mobile-dls-specification

Mobile XMF is a format designed for lightweight audio - It's MIDI + Mobile DLS in a container (you can use both GM patches and custom patches embedded in the .dls)

https://www.midi.org/specifications/file-format-specifications/xmf-extensible-music-format

**Comment by derselbst** [comment]
Sry, but crafting two features into one ticket isn't a good idea. Pls. start a _discussion_ (not issue) for each request. I understand the need for Mobile DLS. A similar discussion has been done in #605, but starved. DLS is more complicated because fluidsynth doesn't support it natively. That said, I don't think any of those changes will ever happen, unless someone actively contributes.
