### ISSUE TITLE
CPU cores not detected?

### ISSUE THREAD

**Issue by Zibri** [FluidSynth/fluidsynth#1066]
OS: Ubuntu 20.04
CPU: Intel(R) Core(TM) i3-3110M CPU @ 2.40GHz

In fluidsynth, typing °settings° the number of detected CPUs is 1.
Should not that be 4?

Also: if I manually set it, it says it's not a realtime setting.

How to use 2 or 4 cores then?

**Comment by mawe42** [comment]
FluidSynth doesn't auto-detect CPU cores. To set any setting (especially non-realtime ones) you can use the `-o` parameter on the command-line. For example:
`fluidsynth ... -o synth.cpu-cores=2 ...`

**Comment by derselbst** [comment]
Default value is one: https://www.fluidsynth.org/api/fluidsettings.xml#synth.cpu-cores

**Comment by Zibri** [comment]
and??? I know the DEFAULT is one... is it possible to use more cores? I changed it to 2 in the source code and recompiled but nothing happened.

**Comment by mawe42** [comment]
Not sure what to make of your comment. You now know that FluidSynth doesn't auto-detect CPU cores, that the default is 1 and that you can change the default by specifying the number of cores with `-o synth.cpu-cores=X`. And of course it's possible to use more than one core... otherwise the setting wouldn't make any sense, would it? ;-)

Is there anything else that you need help with? If so, then please use the Discussions or the fluid-dev mailing-list for usage questions. This issue tracker is for bug reports only.
