### ISSUE TITLE
Unclear Audio File Generation in Windows 10

### ISSUE THREAD

**Issue by prof-spock** [FluidSynth/fluidsynth#1074]
Dear all,

as you might recall I am hunting for the bit-exact reproduction of  command-line fluidsynth as a VST plugin in a DAW (see issue #618).

To get a grip on that I am playing around with the current libfluidsynth (2.2.5, win, x64) using it from a command-line Python or C program in Windows 10. Unfortunately I seem to be too dumb for that. While rendition via audio driver "dsound" works fine, using driver "file" and some WAV output file set by "audio.file.name" does not. Some file gets generated, but it only contains 12ms of audio as opposed to the expected 6s.

Enclosed you'll find the [C_program](https://github.com/FluidSynth/fluidsynth/files/8333978/fileTestFluidSynth.zip). Hopefully you are not too deterred by my renaming of the fluidsynth API functions; they still should have intelligible names.

So I am doing something wrong, but I need some professional hint.

Best regards and thanks for your help in advance!

Prof. Spock

**Comment by derselbst** [comment]
Hello again. And yes, I can reproduce this. I don't see an obvious problem when looking at your code. So I'll need to debug it. I want to do that on Linux, hence we'd need to get rid of the Windows-related lazy loading stuff. I'm currently a bit time-limited. May I ask you to port your code to the standard fluidsynth API? It would probably speed up things a bit.

**Comment by prof-spock** [comment]
Hello derselbst,
thanks for your quick response! I have to apologize for providing such a convoluted source; my naive assumption was that I simply had forgotten some trivial thing.
I have ported the code to the standard (see attachment), but my problem is that nowhere in the standard source distribution from GitHub there is a file named "fluidsynth.h". Hence I emulated it with a local prototype file. Or did I miss something?
Best regards,
Prof. Spock
[fileTestFluidSynth-linux.zip](https://github.com/FluidSynth/fluidsynth/files/8396818/fileTestFluidSynth-linux.zip)

**Comment by derselbst** [comment]
Thanks for the quick conversion! This allowed me to quickly gave it a test on Linux. And surprisingly, it works correctly there. Otherwise it would have been too easy, I guess. Seems like I need to set up my debug environment on Windows now. This may take some time.

**Comment by derselbst** [comment]
Thanks to vcpkg, setting up the debugging env only took 4 hours. Previously, I used to spend days for that. Once done it was surprisingly straight forward to solve. A PR is ready, see above. Pls. try it. Binaries can be found here:
https://dev.azure.com/tommbrt/tommbrt/_build/results?buildId=7341&view=artifacts&pathAsName=false&type=publishedArtifacts

---

A few more hints on your approach of "bit-exact reproduction": Your program is heavily relying on the `sleep()` system call. Sleep() may cause your thread to sleep even longer than you asked for, causing your notes to be played at slightly different times on every program call. Also, fluidsynth is heavily using `sleep` calls internally, given the fact that you used the `file` audio driver.

For sample accurate rendering, I would recommend you to use [fluidsynth's sequencer](https://www.fluidsynth.org/api/Sequencer.html). You'd schedule events either before or while you're rendering audio.

For the rendering process itself, you could add the [fast file renderer](https://www.fluidsynth.org/api/FileRenderer.html) to your program. Basically you'd just keep pumping `fluid_file_renderer_process_block()` until you're done. While rendering, the events are getting processed, depending on how much samples you've rendered, rather than depending on the system timer.

**Comment by prof-spock** [comment]
Hello derselbst,

thanks for your quick analysis and the quick fix!

You wrote:
> fluidsynth is heavily using sleep calls internally, given the fact that you used the file audio driver
> [...] Sleep() may cause your thread to sleep even longer than you asked for
> For sample accurate rendering, I would recommend you to use fluidsynth's sequencer.

Thanks for the hints, I am quite aware of that.
I am still struggling with the difference between using the fluidsynth program exactly in that way to convert a midi file into some audio file on the command-line and converting the same data in realtime via a VST-plugin using libfluidsynth (as mentioned in #618).
The main problem is that I have no idea whether the sequence of samples produced in realtime by libfluidsynth when fed with midi events is identical in principle to that produced via the fast file renderer from a midi file with the same events.
Hence this bit-identical real time file rendering approach might be a complete dead end. I have no real grip on that yet, and maybe also the idea of checking this via the "audio.file" driver is bad due to the points you made. But at least now I can play around with some ideas. 

Best regards,
Prof. Spock

**Comment by prof-spock** [comment]
Hello derselbst,

I have tried your fluidsynth-x64.zip from Azure and it works as expected.
Thanks for your effort!

Best regards,
Prof. Spock

**Comment by derselbst** [comment]
Thanks for the feedback!
