### ISSUE TITLE
Performance is going down or crashes if i load a SF2 file with more than 500GB in the ACE Fluid Synth

### ISSUE THREAD

**Issue by stefan-franz** [FluidSynth/fluidsynth#1193]
### FluidSynth version
I use ACE Fluid Synth with the newest Ardour version - no version nr is displayed on the lv2 plugin. 

### Describe the bug
if i load a SF2 file with more than 500MB in the ACE Fluid Synth of an Ardour project, Ardour crashed sometimes or performance is going down. I have some GM/GS SF2 Packages and ober 500MB they make problems. 
My device: Linux Mint 21 Cinnamon - Governor running with "Performance" setting. - i7 processor and 16 GB Ram.

Developer from Ardour mean, that the problem is on the side of the ACE fluid synth.

**Comment by derselbst** [comment]
Ardour ships a stripped down and customized version of fluidsynth. I will make no attempt to figure out what's wrong on their side. Pls. provide steps on how to reproduce this issue with the fluidsynth commandline tools and if you do, provide the soundfont as well. Otherwise I'll close this issue in a few days.

PS: You should decide whether you're talking about a 500GB or 500MB soundfont.
