### ISSUE TITLE
SoundFonts failing to load

### ISSUE THREAD

**Issue by JimBayne** [FluidSynth/fluidsynth#1203]
Many thanks for this wonderful product. It's amazing. I just implemented it in a .Net Windows based app, for both real time midi instrument audio rendering, and midi sequence playback. The audio quality is great, and the latency is near 0 with an ASIO interface.

The problem I have, is that not all SoundFonts that I have found on the internet load properly. The following code ...

`       sfont_id = fluid_synth_sfload(synth[n], soundfont_filename, TRUE);
	if (sfont_id == FLUID_FAILED)
	{
		sprintf_s(msg, sizeof(msg), "myFluidSynth_Open: Synth # (%d) Failed to load the main SoundFont!\n", (n + 1));
		is_SoundFont = fluid_is_soundfont(soundfont_filename);
		if (is_SoundFont != TRUE) { sprintf_s(msg, sizeof(msg), "%s\n\nFile: %s \n\nIS NOT A VALID SOUNDFONT FILE", msg, soundfont_filename); }
		Message_Box(msg);
		goto Error;
	}`

just says the SoundFonts failed to load (they are not flagged as NOT A  VALID SOUNDFONT FILE, and no other error indicators are available other than the FLUID_FAILED return code )

The list of SoundFonts that I can't load include
* CrisisGeneralMidi3.01.sf2
* Crisis General GM V3.51.sf2
* GiantSoundfontV6.4MelodicBank  and
* GiantSoundfontV6.5MelodicBank
Note these files are huge (1GB+) so I have not uploaded any, but I can if needed.

My system has 16GB of RAM, and 8GB are free most of the time, and I'm using the 32 bit version of FluidSynth.

Any suggestions? Will moving to the 64bit version of FluidSynth solve the problem (which I am hesitant to do unless I have to)

**Comment by ReinholdH** [comment]
x64 definitely helps because for 32 bit the limitation is 4GB for everything. 

However, fluidsynth recently enhanced the capability to only download soundfont samples when they are needed. Usually only a subset of samples are used in typical songs. Please try dynamic-sample loading. See

https://www.fluidsynth.org/api/settings_synth.html#settings_synth_dynamic-sample-loading

We made the experience that the memory consumption for huge soundfont files reduces down to a third or even lower dependent of the required presents. On an x64 app the required memory for GiantSoundfontV6.5MelodicBank.sf2 which is 1.2 GB in size  reduces down to 20% for a typical MIDI file with this option. But I cannot estimate whether the address range for your app is sufficient for 32 bit.

Hope this helps. To me it is not a bug.

**Comment by JimBayne** [comment]
Many thanks. Dynamic sample loading solved the problem for me. 
I added a checkbox for this option, with it turned on by default. Works very well now, and the problem SoundFonts now load and render audio perfectly.
FYI: my app's address space is typically well below 1GB (usually sitting around 200MB without SoundFonts) so I'm guessing 32bit vs 64bit didn't come into play here.
It might be worth incorporating conditional use of Dynamic Sample Loading into the FluidSynth examples. Seems to work very well. Can't see why developers wouldn't want to use it.

**Comment by JimBayne** [comment]
Thanks again!
