### ISSUE TITLE
Implement IPv6 to IPv4 fallback

### ISSUE THREAD

**Issue by derselbst** [FluidSynth/fluidsynth#1208]
### Related discussion
#1205 

### Is your feature request related to a problem?
The `enable-ipv6` cmake option disables IPv4 support, causing fluidsynth's server to fail starting on system which have disabled IPv6 runtime support

### Describe the solution you'd like
Ideally, get rid of the `enable-ipv6` option altogether. This can be done by
* either always trying to open IPv4 and IPv6 sockets, or
* first trying IPv6 and if it fails with `EAFNOSUPPORT` use an IPv4 socket.

### Describe alternatives you've considered
none

### Additional context
Low priority issue, contribution required.

**Comment by ivan-zaera** [comment]
I'm doing this :raised_hand_with_fingers_splayed:. I just need to source format the changes and send the PR.

It's working locally now (tested by starting the server from the command line and connecting from `midieditor` to the daemon).

I've implemented it like this:

> first trying IPv6 and if it fails with EAFNOSUPPORT use an IPv4 socket.

However, I'm still allowing the `enable-ipv6` option because, since it is on by default, leaving it could make sense for people willing to compile the tool with strict IPv4 support.

But if you think it's better to remove it I can try to do it.

**Comment by derselbst** [comment]
Merged and will be part of 2.3.4 - @3hhh FYI.

> I'm still allowing the enable-ipv6 option because

Agreed. Thanks again!

**Comment by 3hhh** [comment]
Nice! Thanks to @ivan-zaera!
