### ISSUE TITLE
Issue with chorus on/off

### ISSUE THREAD

**Issue by brummer10** [FluidSynth/fluidsynth#1241]
### FluidSynth version
FluidSynth runtime version 2.3.1

### Describe the bug
Switch chorus on/off infect the volume of some instruments. Means, the volume drop after switched chorus on and off again. Those happen for example for the 008 004 Detuned EP1 in FluidR3_GM.sf2
I checked the synth.gain parameter, but that on is the same as before.
Not infected is for example 000 001 Yamaha Grand Piano.

### Expected behavior
Expected is that switching chorus off leads to the same output level then before switch in on.

### Steps to reproduce
Load 008 004 Detuned EP1 from FluidR3_GM.sf2, play some Notes, switch chorus on and off, regardless if you play some Notes in between, and play again some Notes, you'll notice a volume drop compared with the output before you've switched on the Chorus, in the output.

### Additional context
I'm using https://github.com/brummer10/Fluida.lv2 to control fluidsynth (I'm the developer of fluida) and noticed that behaviour during the last development circle. I feel I should forward that Issue to you.

regards
hermann

**Comment by derselbst** [comment]
This is by design. Chorus is implemented by delaying a voice, modulating and otherwise amplifying it and put it back to the stereo output. Depending on how many the number of delay lines you've set, this may result in a louder signal than without chorus.

The particular preset `008 004 Detuned EP1` has set the initial chrous generator to 75%, giving it a default chorus effects regardless of CC93. Other presets don't have that set, therefore, they don't have chorus by default and therefore turning chorus on / off doesn't sound different.
