### ISSUE TITLE
fluidsynth command line playback certain MID file missing percussion

### ISSUE THREAD

**Issue by BLumia** [FluidSynth/fluidsynth#1352]
### FluidSynth version

```
$ fluidsynth --version
FluidSynth runtime version 2.3.5
Copyright (C) 2000-2024 Peter Hanappe and others.
Distributed under the LGPL license.
SoundFont(R) is a registered trademark of Creative Technology Ltd.

FluidSynth executable version 2.3.5
Sample type=double
```

### Describe the bug

fluidsynth command line playback certain MID file missing percussion. The MIDI file and soundfont is here: [GK1.zip](https://github.com/user-attachments/files/16201003/GK1.zip), this MIDI file is one of the MIDI files that have the same issue.

### Expected behavior

When play `SEQ_BGM04.mid` with `SEQ_BGM04.sf2` using `fluidsynth` cli, we should be able to hear percussion.

### Steps to reproduce

``` shell
$ fluidsynth.exe SEQ_BGM04.mid SEQ_BGM04.sf2
```

and hear the result.

### Additional context

The MIDI file is extracted with the tool called [vgmtrans](https://github.com/vgmtrans/vgmtrans/) from a game. I'm not quite sure if the file itself is ill-formed or it's a bug of fluidsynth cli, but I also tried to play the same MIDI file with some other software:

- [Timidity++](https://timidity.sourceforge.net/): works fine
- [QMidiPlayer](https://github.com/chirs241097/QMidiPlayer) (which is also based on fluidsynth): works fine
- [Drumstick MIDI File Player](https://dmidiplayer.sourceforge.io/) (with fluidsynth selected): have the same issue
- [vgmtrans](https://github.com/vgmtrans/vgmtrans/) (based on bassmidi, using built-in preview before extract the MIDI and SoundFont file): works fine
- [XMPlay](https://www.un4seen.com/xmplay.html) with [MIDI plugin](https://support.xmplay.com/files_view.php?file_id=500) (based on bassmidi): works fine

Let me know if you need any additional information.

**Comment by spessasus** [comment]
While I'm not a fluidsynth dev, I think I know why that's the case. This file is a *multi port file*, which I don't think fluidsynth supports.
### What is a multi port file?
Multi port file uses the meta message "port prefix" which essentially means 16 channels for each port. In your example, the first channel on port 0 are is program 9 (drums in the provided soundfont), while first channel on port 1 is set to program 12 (marimba). Fluidsynth ignores port prefix and reads it like this:
- set channel 1 to drums
- set channel 1 to marimba
when the file should be read like this:
- set channel 1 on port 0 to drums
- set channel 1 on port 1 to marimba
So the messages end up overlapping and playing the marimba instead of drums.

Here's a screenshot of SpessaSynth controller with your song.
As you can see, the red channel is channel 1. And there are 2 of them, one for each port. Channel 1 on port 0 is drums, while channel 1 on port 1 is marimba.
![image](https://github.com/user-attachments/assets/5e569b7d-dd0c-4e08-a44a-830a7cdf8648)
I hope this clears things up a bit. Cheers!

**Comment by derselbst** [comment]
Thanks for the pointer to the "MIDI port" meta event. But where the hell is that event officially specified?

It's not in "The Complete MIDI 1.0 Detailed Specification" from 1996.
It's not in any of the MIDI 2.0 documents either.
It's not in "RP-019".
It's not in "RP-017".
It's not in "RP-001 - Standard MIDI Files 1.0".
Not even ChatGPT can find any authoritative information.

For now, all I can offer is to log unknown meta events to console.

**Comment by spessasus** [comment]
I didn't discover it through official MIDI spec, but through trial and error. There's this software called Falcosoft MidiPlayer that can play multi port files and I just looked through the event explorer and eventually figured out how it works. But I've found [this website](https://www.mixagesoftware.com/en/midikit/help/HTML/meta_events.html), which has the following:
### MIDI port
FF 21 01 pp

> This optional event which normally occurs at the beginning of a track (ie, before any non-zero time and before any midi events) specifies out of which MIDI Port (ie, buss) the MIDI events in the track go. The data byte pp, is the port number, where 0 would be the first MIDI buss in the system.
> The MIDI spec has a limit of 16 MIDI channels per MIDI input/output (ie, port, buss, jack, or whatever terminology you use to describe the hardware for a single MIDI input/output). The MIDI channel number for a given event is encoded into the lowest 4 bits of the event's Status byte. Therefore, the channel number is always 0 to 15. Many MIDI interfaces have multiple MIDI input/output busses in order to work around limitations in the MIDI bandwidth (ie, allow the MIDI data to be sent/received more efficiently to/from several external modules), and to give the musician more than 16 MIDI Channels. Also, some sequencers support more than one MIDI interface used for simultaneous input/output. Unfortunately, there is no way to encode more than 16 MIDI channels into a MIDI status byte, so a method was needed to identify events that would be output on, for example, channel 1 of the second MIDI port versus channel 1 of the first MIDI port. This MetaEvent allows a sequencer to identify which track events get sent out of which MIDI port. The MIDI events following a MIDI Port MetaEvent get sent out that specified port.
> It is acceptable to have more than one Port event in a given track, if that track needs to output to another port at some point in the track.

I've managed to implement this and I did it as follows (note: this isn't official or anything but all multi port midis i have seem to work fine):
1. [While parsing the file, assign each track the port -1.](https://github.com/spessasus/SpessaSynth/blob/50f08c9db1a1dc2d74417e6fa7de8d5b91b9bbe1/src/spessasynth_lib/midi_parser/midi_loader.js#L90)
2. [When the message is encountered, assign the port to the track it's on.](https://github.com/spessasus/SpessaSynth/blob/50f08c9db1a1dc2d74417e6fa7de8d5b91b9bbe1/src/spessasynth_lib/midi_parser/midi_loader.js#L236)
3. [Once finished, set all ports -1 to the smallest port found, otherwise 0. (See the code as there's a comment explaining why i do that this way)](https://github.com/spessasus/SpessaSynth/blob/50f08c9db1a1dc2d74417e6fa7de8d5b91b9bbe1/src/spessasynth_lib/midi_parser/midi_loader.js#L304)
4. [When playing the song: for each port:](https://github.com/spessasus/SpessaSynth/blob/50f08c9db1a1dc2d74417e6fa7de8d5b91b9bbe1/src/spessasynth_lib/sequencer/worklet_sequencer/song_control.js#L45)
5. - assign a channel offset. Start with 0 and for each new port (no matter the number) add 16.
    - add 16 channels if the offset + 15 is more than channel count.
6. [When processing the event, take the 4-bit channel number and add the track's port offset to it.](https://github.com/spessasus/SpessaSynth/blob/50f08c9db1a1dc2d74417e6fa7de8d5b91b9bbe1/src/spessasynth_lib/sequencer/worklet_sequencer/process_event.js#L25)
[Here are some multi-port midi files to help test the feature.](https://github.com/user-attachments/files/16216556/multi_port_collection.zip)
I hope this helps, cheers!

**Comment by derselbst** [comment]
Ok, thanks. So for the record: This MIDI file relies on an unofficial meta event, which I and fluidsynth have never heard of before. This is not a bug.

I have also found plenty of implementations and websites referring to this event - but no authoritative specifications from MMA or similar. If someone is willing to draft a PR for this, pls. provide an official document by MMA  / midi.org. Fluidsynth's built-in MIDI player is very basic and I don't want to accept any unofficial extension that someone has crafted to the MIDI standard.

**Comment by spessasus** [comment]
Doesn't fluidsynth support GS and XG?
From wikipedia:
> Yamaha XG (EXtended General MIDI) is an extension to the General MIDI standard, created by Yamaha.

This standard is not from MMA and yet it's supported. Same with GS.

I would definitely suggest adding this feature, especially since most of the complex arrangements from Musescore seem to heavily rely on it. 
Maybe an option like `-o synth.enable-multi-port` that defaults to false? A lot of players (as described by the original reporter) already support it so why fluidsynth wouldn't?

**Comment by derselbst** [comment]
> This standard is not from MMA and yet it's supported. Same with GS.

I would also accept a document from XG or GS. If it's officially part of any of those, it would be enabled by default without needing an extra commandline option.

Currently, I don't have such a document or any other official reference, hence I'm considering it an unofficial extension.
