### ISSUE TITLE
Error during initialization in Flutter project when using version 2.3.6, but not in 2.3.4

### ISSUE THREAD

**Issue by lzxyh0227** [FluidSynth/fluidsynth#1402]
The crash occurs during initialization when loading the soundfont file in Flutter, but it works fine on Android projects across all devices.

Device: Redmi Note 13 Pro
System: Android
Error Method: fluid_synth_sfload()
Log details:
D/FLUID_SYNTH(12784): testcccc   print_log: Using OpenSLES driver.  
F/libc    (12784): Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 27431 (AudioTrack), pid 12784 (c_score_example)
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'Redmi/garnet/garnet:13/TKQ1.221114.001/V14.0.18.0.TNRCNXM:user/release-keys'
Revision: '0'
ABI: 'arm64'
Timestamp: 2024-10-08 18:19:29.471013613+0800
Process uptime: 2982s
Cmdline: com.xihang.flutter_sdk_music_score_example
pid: 12784, tid: 27431, name: AudioTrack  >>> com.xihang.flutter_sdk_music_score_example <<<
uid: 10238
...
backtrace:
    #00 pc 000000000008d974  /apex/com.android.runtime/lib64/bionic/libc.so (abort+168) (BuildId: 73ff06a849c14c12e55ab2ccc339618d)
    #01 pc 000000000003cae4  /data/app/.../lib/arm64/libomp.so (BuildId: 4b6a70c41e8bde326879358605c3d07a8b4c73c4)

**Comment by derselbst** [comment]
I have no Android, I have no Flutter. Please provide a full backtrace with a debug build of fluidsynth that includes links to fluidsynth's source code. Otherwise, I have no means to reproduce this and will be forced to close this as won't fix. Also, source code that demonstrates the usage of fluidsynth would be helpful, only claiming "fluid_synth_sfload()" without any parameters and any context of how it's used is not helpful.
