### ISSUE TITLE
Broken MIDI playback

### ISSUE THREAD

**Issue by human222** [FluidSynth/fluidsynth#1425]
While testing some X68000 games, I noticed that the music is broken in exactly the same way in every emulator. It looks like the issue is that FluidSynth is refusing to play some MIDI channels.

### Steps to reproduce
1. Type "fluidsynth" in the terminal to start FluidSynth.
2. Run "Detana! Twin Bee" in any X68000 emulator (I tested MAME, XM6 Type-G and px68k-libretro), with FluidSynth as the MIDI Out device. A real X68000 would probably have the same result too.
3. Start the first stage and the issue should be obvious right away.

### Additional context
FluidSynth:

https://github.com/user-attachments/assets/acc9b68b-9e6d-4454-ad87-4abc4b73a0f8

Falcosoft MidiPlayer:

https://github.com/user-attachments/assets/6c550cdd-37d9-4948-9cc7-863120ab9435

-Tested on Fedora 41. Both Fedora's rpm and my self-compiled build of 2.4.0 were tested.
-Tested with GeneralUser-GS soundfont with recommended settings.
-Any synthesizer other than FluidSynth appears to work fine.
-Falcosoft MidiPlayer can use soundfonts and should be easy to compare against.

**Comment by derselbst** [comment]
Please provide a MIDI file. You can record the MIDI output with `arecordmidi`.

**Comment by human222** [comment]
Thanks for suggesting arecordmidi. Here is a MIDI file:

https://easyupload.io/vi9ofl

FluidSynth will start to trip up around 30 seconds in when the game's first stage starts.

**Comment by ReinholdH** [comment]
The reason is that at ~31 seconds the "c = 126, v = M: Mono Mode On (Poly Off) where M is the number of channels (Omni Off) or 0 " is set. Please see

![Mono_Mode_On_channel_1_at_31_seconds](https://github.com/user-attachments/assets/1d12b8cb-997a-4b48-b4fe-71bfa4441608)

This is the spec
https://midi.org/summary-of-midi-1-0-messages

Here is a good description what Mono Mode On/Off does
http://midi.teragonaudio.com/tech/midispec/modes.htm

I took the liberty to delete this controller event and all channels sound properly now. Please listen to MIDI file attached.
[twinbeetest_Mono_Mode_On_removed.zip](https://github.com/user-attachments/files/17675766/twinbeetest_Mono_Mode_On_removed.zip)
This MIDI file looks as if there are MIDI files simply appended. Lots of SysEx Reset and Controller Resets all over the place. I have never seen such a MIDI file (where I believe that I have analyzed 1000s...).

Probably all the other synthesizer ignore "c = 126, Mono Mode On" because such an event does not make any sense and is rarely used in practise. See https://audiointerfacing.com/what-are-midi-modes/#midi-mode2

To me this is not bug in fluidsynth. fluidsynth complies to the spec. IMO the MIDI file is simply bad.

**Comment by human222** [comment]
> To me this is not bug in fluidsynth. fluidsynth complies to the spec. IMO the MIDI file is simply bad.

This kind of stance breaks compatibility. Real-world usage trumps specs IMO.

**Comment by derselbst** [comment]
Thanks for the MIDI file. I also had a look into this. I can basically confirm what Reinhold has already discovered. I have added additional console logs to make it more obvious, when a basic channel config is changed (or has failed to change).

So essentially, the MIDI first tries to set channels 3,5,6 to POLY_OFF. But this fails, because those channels are no basic channels.

The one and only basic channel is channel 0. The MIDI then reconfigures that channel to POLY_OFF. By doing so it deletes the basic channel and with that the entire channel group, which means it implicitly disables channels 1-15, without reconfiguring those channels. Because of this, those channels do no longer respond to any note event.

PolyMono functionality was added in version 2.0.0 to fluidsynth. Behavior that complies to a specification is very important to fluidsynth. Yes, there are a few points here and there esp. in the SF2 spec that we handle more permissively. But this is not applicable in this case - here, the provided MIDI is the outlier, sry.

Your best option is to add a midi router in between which filters out the MIDI CCs 124 - 127 of all channels.

**Comment by spessasus** [comment]
> > To me this is not bug in fluidsynth. fluidsynth complies to the spec. IMO the MIDI file is simply bad.
> 
> This kind of stance breaks compatibility. Real-world usage trumps specs IMO.

@human222, i then suggest sticking to BASSMIDI (e.g. falcosoft MIDI player), since it's more oriented towards retro gaming. It includes support for way more system exclusives, emulates retro hardware (SB soundcards) and applies custom default modulators to various controllers and NRPNs for a broader support without requiring modulators.

Fluid on the other hand is meant to be an accurate and compliant midi synth, sticking to the spec wherever it can. So it's not suitable for your use case.

**Comment by human222** [comment]
Thanks, that's good to know. FluidSynth is often recommended for all MIDI playback, but I will stick to BASSMIDI as you said.
