### ISSUE TITLE
voice with high filter Q killed too early, causing audible click

### ISSUE THREAD

**Issue by mrbumpy409** [FluidSynth/fluidsynth#1427]
### FluidSynth version
Affects 2.3 (and presumably older) and 2.4 versions of FluidSynth including current master and iir-tests branches.

### Describe the bug
By default FluidSynth cuts off a voice after the volume envelope release has reached -96 dB (as I recall... I'm going off of memory here). Normally the volume envelope being at -96 dB would be an inaudible cutoff, but when high filter Q is used, the filter hasn't stopped "ringing" at this point, and so the still audible sound is abruptly cut off, resulting in a click.

### Steps to reproduce
1. Download and extract the following zip file: 
[high_Q_note_cutoff_test.zip](https://github.com/user-attachments/files/17704226/high_Q_note_cutoff_test.zip)
2. Load the .sf2 file into FluidSynth and play the .mid file. I have also included an audio file `fluidsynth_iir-tests.flac` showing the result of this test using FluidSynth's current iir-tests branch.

### Current behavior
The voice cuts off while the filter is still resonating, causing an audible click. You can see this quite clearly by viewing the waveform in Audacity: 
![image](https://github.com/user-attachments/assets/72d7b9a5-81c1-4a02-a922-b37e0a1286c6)

### Expected behavior
The voice shouldn't be cut off until the filter output has also reached -96 dB.

### Additional context
Related to bug #1415.

**Comment by spessasus** [comment]
This is strange. It seems that the filter is not being affected by the final gain amplifier and instead is being sent directly to the final output.

According to Section 9.1.8 of the sf2 specification:
![image](https://github.com/user-attachments/assets/49ef80c2-612c-42e9-8a41-70fa2548127b)

The gain should come after the filtered output, so the ringing should ramp to -96dB too. This happens when playing the `Whistlewind` in Polyphone.

**Comment by derselbst** [comment]
Thanks again for the report. I didn't found time to look into this, but here are two thoughts:

> By default FluidSynth cuts off a voice after the volume envelope release has reached -96 dB (as I recall... I'm going off of memory here)

We wanted to in #319, but it didn't happen. On the other hand, there is that logic around "noise floor" that might explain the effect observed here:

https://github.com/FluidSynth/fluidsynth/blob/168183c3b63efdf43ec07449a1a921c2c7b63868/src/rvoice/fluid_rvoice.c#L52

> It seems that the filter is not being affected by the final gain amplifier and instead is being sent directly to the final output.

Yes, because the SF spec asks for a gain compensation dependent on Q, which we currently do here:

https://github.com/FluidSynth/fluidsynth/blob/168183c3b63efdf43ec07449a1a921c2c7b63868/src/rvoice/fluid_iir_filter.c#L204-L215

But it's amount is only half of Q's peaks.

I need to investigate how both are related to explain the observed effect here.

**Comment by spessasus** [comment]
> Yes, because the SF spec asks for a gain compensation dependent on Q, which we currently do here

That's an additional gain. it doesn't mention anywhere that only the Q Gain should be applied to the filter, but according to the diagram, it shows that the filter is affected both by Q and volEnv. It honestly makes sense and doing that does not cause any clicks since the ringing gets attenuated too.

Not to mention that:

> 9.1.4  Final Gain Amplifier
> The final gain amplifier is a **multiplier on the filter output**, which is controlled by an initial gain in dB.  This is added to the volume envelope.  Additional modulation can also be added.  The gain is always specified in dB. 

It does explicitly state that the final gain amplifier uses the filtered input and not wavetable oscillator.

**Comment by derselbst** [comment]
I made a quick and dirty implementation of my previous idea by just keep feeding the filter with zero samples forever after the voice has finished. The result looks like this:

![Screenshot_20241207_180529](https://github.com/user-attachments/assets/b382a932-3f6c-4e22-bc48-60fe30b85c3c)

On the bottom: the previous cutoff behavior, on top the new "filter-drained" behavior. Take a listen yourself:

[1427_high-Q-note-cutoff.zip](https://github.com/user-attachments/files/18049260/1427_high-Q-note-cutoff.zip)

Obviously, this approach will completely ruin the release envelope. Yet, if you consider it an acceptable solution, I have to figure out how long we're going to "drain" the filter this way, before we can truly turn off the voice.

**Comment by spessasus** [comment]
Why not just feed the filter into the gain amplifier like I've suggested earlier?
Even the section 9.1.4 does specify that the filtered output should go into the volEnv gain input.

**Comment by derselbst** [comment]
The gain of the volEnv is applied when fluidsynth interpolates the voice buffers to the output sample rate in `fluid_rvoice_dsp*()`.

Therefore and from my understanding, you're suggesting to move the call to `fluid_iir_filter_apply` here https://github.com/FluidSynth/fluidsynth/blob/d814a62db8d40b30db2fbcac69a45ace207e80ed/src/rvoice/fluid_rvoice.c#L491

a few lines up before the `fluid_rvoice_dsp*()` calls. Yes, this would also attenuate the filtered output in accordance to the volEnv. I see two possible issues here:

The IIR filter has a dependency to the "output_rate", here

https://github.com/FluidSynth/fluidsynth/blob/d814a62db8d40b30db2fbcac69a45ace207e80ed/src/rvoice/fluid_iir_filter.c#L271-L272

This is currently set to the synth's `output_rate`. We would need to access the sample's original sample_rate via `voice->sample->samplerate`. This might change the behavior of the filter and the filter cutoff in particular, as it affects `omega` inside the filter.

Also note that `fluid_rvoice_dsp*()` is responsible for pitching. So instead of applying the pitch before the filter, it would be applied on the filtered signal. That should be fine though, since it's a linear system.

Ok, I'll try that.

**Comment by spessasus** [comment]
I'm suggesting the same thing my synth is doing.

I.E.:
1. wavetable oscillator (with pitch control) fills the buffer
2. filter applied to the buffer
3. volume envelope applied to the buffer
4. the buffer goes wherever it needs to go (probably the panning node if fluid doesn't do any custom processing after that)

https://github.com/spessasus/SpessaSynth/blob/23d4bd96c04ac6f5e95d0d45052a7059107e7afe/src/spessasynth_lib/synthetizer/worklet_system/worklet_methods/voice_control.js#L158-L185

I hope this clears things up.

**Comment by derselbst** [comment]
Ok, I found a solution that integrates quite well. Here is the result:

[1427_high-Q-note-cutoff_filter-before-volenv.zip](https://github.com/user-attachments/files/18049933/1427_high-Q-note-cutoff_filter-before-volenv.zip)

Essentially, the IIR filter is now run on-the-fly inside the sample interpolation. Though this means that only a single sample can ever be processed by the IIR filter at a time (rather than previously 64 samples in one go),  it also eliminates the need to re-read the samples from memory. I do like that solution, thanks for your persistence! I'll open a PR shortly.

**Comment by mrbumpy409** [comment]
So far in my testing of the pull request, everything sounds great! All clicking on release is gone, and I haven't noticed any regressions.

**Comment by derselbst** [comment]
Thanks for the feedback Chris, glad to hear that!
