### ISSUE TITLE
Extra time added to wav in the midi to wav conversion

### ISSUE THREAD

**Issue by miguelriemoliveira** [FluidSynth/fluidsynth#1433]
### FluidSynth version
FluidSynth runtime version 2.3.4
Copyright (C) 2000-2023 Peter Hanappe and others.
Distributed under the LGPL license.
SoundFont(R) is a registered trademark of Creative Technology Ltd.

FluidSynth executable version 2.3.4
Sample type=double

### Describe the bug
I am not sure if this is a bug. I will describe it. 
When I convert a midi file to a wav file, the wav file will always have an extra 2 or 3 seconds in comparison to the midi.

Not sure if this added time is always the same or not.

### Expected behavior
I would expect the wav to have the same duration as the midi.

### Steps to reproduce

Get a midi file and run:

    fluidsynth -ni /usr/share/sounds/sf2/default-GM.sf2 mymidi.midi -F mywav.wav -r 22050

And the wav file should have a bit more total time (some 2 secs) than the midi.

Thanks in advance for the help.

**Comment by spessasus** [comment]
That's because fluidsynth waits for all sounds to get silent. This is intentional behavior AFAIK. 

If it was to stop the rendering on the last event, the music would end abruptly and there would be no time for the instruments to fade away (like drums for example.)

**Comment by derselbst** [comment]
As already explained, this is intentional and not a bug.

> From what I could read, there is currenlty no way of doing this, right?

Fluidsynth has a powerful API. If you need a custom playback, I'd recommend to use the MIDI sequencer together with the synth:
https://www.fluidsynth.org/api/Sequencer.html

But instead of using an audio driver, you should use the fast file renderer and keep rendering until the sequencer has ran out of events, cf:
https://www.fluidsynth.org/api/FileRenderer.html

**Comment by miguelriemoliveira** [comment]
Thanks for the responses. Best regards.

**Comment by derselbst** [comment]
That's because fluidsynth is under active development, pls. consult the changelog:
https://github.com/FluidSynth/fluidsynth/wiki/ChangeLog
