### ISSUE TITLE
Modulation envelope attack is linear instead of convex

### ISSUE THREAD

**Issue by derselbst** [FluidSynth/fluidsynth#153]
According to the [2.01/2.04 spec](http://freepats.zenvoid.org/sf2/sfspec24.pdf), both the volume and modulation envelopes should have a convex attack phase. FluidSynth correctly uses a convex attack for the volume envelope, but uses a linear attack for the modulation envelope.

You can hear the difference by comparing the two "modulation envelope test" OGG recordings (inside attached archive) between the Audigy 2 ZS and FluidSynth. In the recording, you will hear a single note playing through all stages of a modulation envelope that is mapped to the note's pitch. Hear the difference in the speed/curve of the initial rise in the note's pitch. The similarly-named .mid and .sf2 files can be used to test this yourself.

Reported by: mrbumpy409

Original Ticket: [fluidsynth/tickets/155](https://sourceforge.net/p/fluidsynth/tickets/155)

**Comment by mrbumpy409** [comment]
[modulation envelope test.tar.gz](https://github.com/FluidSynth/fluidsynth/files/1186342/modulation.envelope.test.tar.gz)

**Comment by jjceresa** [comment]
>Here are the test files from my original bug report on the SourceForge bug tracker.

Hello, (since more than one year now !).Thanks a lot for this important missing archive.

>although I tend to think that if you want to be able to customize envelope curves and filter types, etc., that is what a sampler format such as SFZ is for.

Not yet familiar with this format, after a quick look there are  SFZ 1.0 and SFZ 2.0 and both are official but only SFZ 1.0 is documented. Did you know if SFZ 2.0 documentation is accessible elsewhere ? or may be could you advice about preference between both ?

**Comment by mrbumpy409** [comment]
The "official" documentation on the SFZ 2.0 specs was only ever published in the book Cakewalk Synthesizers: From Presets to Power User<https://www.amazon.com/Cakewalk-Synthesizers-Presets-Power-User/dp/1435455649/>. However, fairly comprehensive documentation can also be found at the following links:

  *   sfz format mappings<http://www.drealm.info/sfz/>
  *   sfz format<http://www.drealm.info/sfz/plj-sfz.xhtml>
  *   LinuxSampler SFZ Reference<https://docs.google.com/document/d/1UxPar5toq2uDrU4Gkf4jOGzV3ic-CAoRPo0cWE6xino/pub>

You can also find a good discussion group for SFZ programming here<https://plogue.com/phpBB3/viewforum.php?f=14>.

Peace,

-~Chris

On 12/23/2017 12:56 PM, jjceresa wrote:

Here are the test files from my original bug report on the SourceForge bug tracker.

Hello, (since more than one year now !).Thanks a lot for this important missing archive.

although I tend to think that if you want to be able to customize envelope curves and filter types, etc., that is what a sampler format such as SFZ is for.

Not yet familiar with this format, after a quick look there are SFZ 1.0 and SFZ 2.0 and both are official but only SFZ 1.0 is documented. Did you know if SFZ 2.0 documentation is accessible elsewhere ? or may be could you advice about preference between both ?

**Comment by derselbst** [comment]
> Second, the actual linear shape for Mod Attack, seems to be musically useful. So keeping this option inside Fluidsynth would be interesting. [...] Of course that means that at Soundfont design time, we always need to think and maintain two set of Soundfonts;

The fact that fluidsynth uses a linear modenv attack is a bug. The spec is absolutely clear to use a convex shape (whether we like it or not). And because to avoid having to think about two versions of soundfonts out there, I dont want to introduce any setting for this.

**Comment by derselbst** [comment]
Implemented by #406.
