### ISSUE TITLE
the default "pitch wheel -> fine tune" modulator can't be removed

### ISSUE THREAD

**Issue by derselbst** [FluidSynth/fluidsynth#154]
The default modulators are normally "turned off" by adding an identical instrument-level modulator and setting the amount to 0. This works in FluidSynth for the other default modulators I have tested (although I haven't tested all of them). However, for the "pitch wheel -> fine tune" modulator, this isn't working correctly.

I have created a test SoundFont (attached) containing three notes, each with a different modulator setup:

**Note:** F#6
**Local modulators:** none
**Resulting pitch bend:**
    **Audigy 2 ZS:** normal
    **FluidSynth:** normal

**Note:** G6
**Local modulators:**
    **1.** Source1=Pitch Wheel (Linear, Bipolar, +)
        Source2=Bend Range (Linear, Unipolar, +)
        Destination=Fine Tune
        Amount=0
        **NOTE:** this should "turn off" the default "pitch wheel -> fine tune" modulator, resulting in pitch bend having no effect.
**Resulting pitch bend:**
    **Audigy 2 ZS:** none
    **FluidSynth:** normal *<-- should be "none"*

**Note:** G#6
**Local modulators:**
    **1.** Source1=Pitch Wheel (Linear, Bipolar, +)
        Source2=Bend Range (Linear, Unipolar, +)
        Destination=Fine Tune
        Amount=0
        **NOTE:** this should "turn off" the default "pitch wheel -> fine tune" modulator, resulting in pitch bend having no effect.
    **2.** Source1=Pitch Wheel (Linear, Bipolar, -)
        Source2=Bend Range (Linear, Unipolar, +)
        Destination=Fine Tune
        Amount=12700
        **NOTE:** this should create an inverted pitch bend (i.e., pitch wheel up will cause the pitch to bend down, and vice versa).
**Resulting pitch bend:**
    **Audigy 2 ZS:** inverted
    **FluidSynth:** none *<-- should be "inverted"*

The attached MIDI file and OGG recordings feature all three of the above notes played in succession with the pitch wheel bending downward, back to 0, upward, and back to 0. You can hear the aforementioned differences clearly when comparing the Audigy 2 ZS and FluidSynth recordings.

Reported by: mrbumpy409

Original Ticket: [fluidsynth/tickets/156](https://sourceforge.net/p/fluidsynth/tickets/156)

**Comment by jjceresa** [comment]
Be able to cancel the `default modulator` (sfspec24- p44 - 8.4.10 `MIDI Pitch Wheel to Initial Pitch` ) is legitimate and useful when one wants to use the `MIDI Pitch Wheel general controller` to modulate another generator. Actually in fluidsynth this is impossible to do. (This would be possible if the soundfont spec. had not forgotten to enumerate properly this Initial Pitch generator in the table `sfspec24 - p44 - 8.1.2` ).

To fix this issue, I see 2 solutions:
1) We decide that Initial Pitch generator that is actually internally assigned (GEN_PITCH) to number `59` must be documented and published as a valid Generator usable in soundfont File.

2) We change the destination of default modulator (sfspec24- p44 - 8.4.10 MIDI Pitch Wheel to Initial Pitch )  to destination fine tune (i.e GEN_FINETUNE).

Solution 2  seems preferable but it is not obvious because `min max` range values aren't the same as for `Initial Pitch`.

Opinions ?.

**Comment by jjceresa** [comment]
Be able to cancel `default modulator` (sfspec24- p44 - 8.4.10 `MIDI Pitch Wheel to Initial Pitch` ) is legitimate and useful when one wants to use the `MIDI Pitch Wheel general controller` to modulate another generator. 
Actually in fluidsynth this is impossible to do. This would be possible if the soundfont spec. had not forgotten to enumerate properly this `Initial Pitch generator` in the table (sfspec24 - p44 - 8.1.2 ).

To fix this issue, I see 2 solutions:

1)We decide that `Initial Pitch generator actually internally assigned (GEN_PITCH) to number `59`, must be documented and published as a valid generator usable in soundfont File.

2) We change the default modulator destination Initial Pitch  to destination fine tune (i.e`GEN_PITCH`  replaced by `GEN_FINETUNE`).

Solution 2 seems preferable but it isn't obvious because `GEN_FINETUNE` unit and min max range values aren't the same as for `Initial Pitch`.

Opinions ?.

**Comment by jjceresa** [comment]
Be able to cancel default modulator (sfspec24- p44 - 8.4.10 MIDI `Pitch Wheel to Initial Pitch` ) is legitimate and useful when one wants to use the `MIDI Pitch Wheel` controller to modulate another generator.
Actually in fluidsynth this is impossible to do. This would be possible if the soundfont spec. had not forgotten to enumerate properly this `Initial Pitch` generator in the table (sfspec24 - p44 - 8.1.2 ).

To fix this issue, I see 2 solutions:

1)We decide that `Initial Pitch` generator actually internally assigned (GEN_PITCH) to number `59`, must be documented and published as a valid generator usable in soundfont File.

2)We change the default modulator destination `Initial Pitch` to destination `fine tune` (i.e `GEN_PITCH` replaced by `GEN_FINETUNE`).

Solution 2 seems preferable but it isn't obvious because `GEN_FINETUNE` unit and min max range values aren't the same as for `Initial Pitch`.

Opinions ?.

**Comment by derselbst** [comment]
> useful when one wants to use the MIDI Pitch Wheel controller to modulate another generator.

Unconventional, but with the benefit that pitchwheel is the only controller with 14 bit precision.

> To fix this issue, I see 2 solutions:

Solution 2) has the benefit it will be usable with existing (and unmaintained) soundfont editors. However, using "fine tune" as destination generator whereas the spec requires "initial pitch" isn't obvious indeed. So I think, whatever solution we agree on, it must be correctly documented anyway.

> GEN_FINETUNE unit and min max range values aren't the same as for Initial Pitch.

... and fortunately for fluidsynth this doesn't seem to matter (?).

In any case, JJC you are welcome to draft a PR :)

**Comment by jjceresa** [comment]
>Unconventional, but with the benefit that pitchwheel is the only controller with 14 bit precision.

Yes, unconventional, but  really useful as many MIDI controller keyboard have natively this hardware 
immediately accessible (by hand) when playing performance. A skilled pianist (not necessarily professional) have frequently his 2 hands and at least one foot busy while playing. Ease access to these CC device, and ease routing of these devices, while playing is a very important aspect.

>Solution 2) has the benefit it will be usable with existing (and unmaintained) soundfont editors.

Yes, conversely solution 1) which is straightforward,  have the boring drawback to force soundfont designer (having the habit to designate  'fine tune')  to maintain two set of soundfont , because of the new generator '59'.

Also, for (unmaintened) soundfont editor that only presents to the designer `named generator` (eg "Fine tune") instead of numbered one ;  solution 1 will never be useful !

>GEN_FINETUNE unit and min max range values aren't the same as for Initial Pitch.
>... and fortunately for fluidsynth this doesn't seem to matter (?).

Assuming solution 2 option, I haven't yet look if extending max,min of `GEN_FINETUNE` to the actual values of `GEN_PITCH` will cause an issue. For now the only relation I see with GEN_FINETUNE is  `RPN_CHANNEL_FINE_TUNE` which have 14 bit values. 

I am torn between solution (1) and (2)....!

**Comment by mawe42** [comment]
I would vote got go with option 2., mainly because that way Fluidsynth would behave just like the Audigy 2 ZS (according to the original bug report by Christian Collins). As the soundfont spec doesn't help us here, I think taking the actual hardware implementation as a guideline is the next best thing.

**Comment by jjceresa** [comment]
Option 2 seems a good choice. It is compatible with RPN_CHANNEL_FINE_TUNE which have 14 bit values (like Pitch Wheel). Also, I don't see that this will break something in FluidSynth.

Also, I realized that option 1 isn't not  good because actually internally Initial Pitch (GEN_PITCH) isn't intended to be modulated. May be this is why Initial Pitch isn't  enumerated in the SF specification.

**Comment by jjceresa** [comment]
>Assuming solution 2 option, I haven't yet look if extending max,min of GEN_FINETUNE to the actual values of GEN_PITCH will cause an issue.

I have looked this. It looks fortunately that  `max,min` ranges for both `GEN_PITCH` and GEN_FINETUNE aren't used.

**Comment by derselbst** [comment]
Attaching Christophs original test file.

[pitch bend modulator test.tar.gz](https://github.com/FluidSynth/fluidsynth/files/3825144/pitch.bend.modulator.test.tar.gz)
