### ISSUE TITLE
Mixed whitespace

### ISSUE THREAD

**Issue by markh-de** [FluidSynth/fluidsynth#179]
My OCD (just kidding) is asking me to fix FluidSynth's source-code whitespace, as I have noticed that it contains mixed-style tabs and spaces. We even have one line with "misleading indentation", which will be fixed when cleaning up.
What is your project-specific whitespace/indentation policy? Personally (and professionally) I prefer 2 spaces per level, no tabs.
Also, any interest to pass the code through clang-format or uncrustify, while we're at it?
Or are you worried about messing up the file history (e.g. for "blame")?
I already made a fork and would send you PRs when I got something. Is that OK for you?

**Comment by derselbst** [comment]
Yes, I agree it's inconsistent and it's good to see that someone cares.

> What is your project-specific whitespace/indentation policy?

Not sure, there doesnt seem to exist any written style guide and I dont want to bother the former maintainers with that topic. What I can tell from the sources is that it seems we are using K&R brace placement and 4 spaces indentation. Though I personally prefer Allman brace placement, I think it's better to stick to fluidsynths conventions.

> Also, any interest to pass the code through clang-format or uncrustify, while we're at it?

clang-format sounds like a really good idea. Feel free to prepare the source and submit a PR. However: I will not accept any code re-formatting before the next major release (i.e. 1.2 or 2.0, whatever it'll be called). This is because I want to merge in the changes done by several custom forks here (SF3 support, lyrics support, API for manip def. mod., ...) and whitspace changes will make it harder to trace back changes.

Anyway, this issue is suited to be done before the next major release, after all the dev work, API adjustment and making-fluidsynths-folder-structure-github-friendly work is done :)
