### ISSUE TITLE
Reorganize how tunings are handled and tuning API

### ISSUE THREAD

**Issue by LiamM32** [FluidSynth/fluidsynth#213]
Firstly, the default equal temperament (not "Well temperament" like the wiki calls it) should be treated like other tunings, rather than the state of "no tuning".  The default tuning should appear as any other tuning when listing all available tunings.  There should be no such thing as a channel set to "no tuning", but it will be set to this one by default.

Secondly, do we really need to have tunings sorted in banks?  I don't think we do.  If we ditch banks, then the default tuning will always be Prog 0.  But if we must have banks, then the default equal temperament should be the sole tuning in Bank 0, and setting a channel to any Prog in Bank 0 would set it to the default equal temperament, while the other banks are used for custom tunings.

It is very problematic that the API has no function to find what tuning a channel is set to.

There is also some redundency in the API.  If I understand correctly, "fluid_synth_create_key_tuning()" does the same thing as "fluid_synth_activate_key_tuning()" with the last parameter set to "false", so why do we even have the former function?  The former function is a bool that returns false when it doesn't work, so the latter function should also be a bool.  These should just be merged into one function.
"fluid_synth_tuning_dump()" should also be turned into a bool that returns false if it doesn't change the values of the array stored in the "pitch" parameter.

It would also be nice to have a setting to have all channels set to the same tuning.

**Comment by derselbst** [comment]
> If I understand correctly, "fluid_synth_create_key_tuning()" does the same thing as "fluid_synth_activate_key_tuning()" with the last parameter set to "false", so why do we even have the former function?

It's all due to providing a backwards compatible API. `fluid_synth_create_key_tuning` existed first, but apparently someone came up saying: "Hey I need the tuning to take effect immediately." Since existing functions shall usually not be changed in order to provide a compatible API, `fluid_synth_activate_key_tuning` was introduced.

> The former function is a bool that returns false when it doesn't work, so the latter function should also be a bool.

Be careful with your nomenclature: They dont return bools, they return either `FLUID_OK` or `FLUID_FAILED`, which can be anything.

> so the latter function should also be a bool.

Looking at the code they both consistently return either `FLUID_OK` or `FLUID_FAILED`.

> "fluid_synth_tuning_dump()" should also be turned into a bool that returns false if it doesn't change the values of the array stored in the "pitch" parameter.

It correctly returns `FLUID_FAILED` if it fails. Dont see the problem.

> These should just be merged into one function.

Yes, I agree it's confusing. We will have an API cleanup anyway, so that's on the ToDo list (#167).

> the default equal temperament (not "Well temperament" like the wiki calls it)

To what wiki page are you referring?

---

For the rest of your problem I have to admit that I have no real experience using this tuning stuff and I dont know why they have been implemented as they are (there probably is a connection with MIDI SysEx tuning messages, but I'm currently not familiar with that).

Perhaps you could give a little more input on what your underlying use case or problem is.

**Comment by LiamM32** [comment]
> It's all due to providing a backwards compatible API. fluid_synth_create_key_tuning existed first,
Well then;  We should have it marked "deprecated".  On the wiki page, deprecated functions should be moved to their own section at the bottom of the page.

> They dont return bools, they return either FLUID_OK or FLUID_FAILED
Sorry. I don't know how I misread it before.  They are actually "int".  But one problem that I see, is that according to [this page](http://www.fluidsynth.org/api/misc_8h.html#ae4efb1c3ce0d550c922504adfb0fb886), "FLUID_OK" is 0, while "FLUID_FAILED" is -1.  Doesn't this go against conventions of 0 being "false"?  Won't this mean that the line `if (fluid_synth_function())` will do the opposite of what someone would expect?

> To what wiki page are you referring?
I've seen it in multiple places.  [Here](http://www.fluidsynth.org/api/synth_8h.html#aa45d7358ae0d5f246df314402847dea3) you can see the incorrect terminology for `fluid_synth_reset_tuning()`, while the next function is described correctly.  Using _Ctrl+f_, I found there are 4 instances of "well-tempered" on that page (all incorrect).  I don't know how to edit the wiki, unfortunately.

**Comment by derselbst** [comment]
>  We should have it marked "deprecated".

Don't know why they haven't been deprecated, but I agree.

> On the wiki page, deprecated functions should be moved to their own section at the bottom of the page.

The wiki is the wrong place. There already is a dedicated page in the devdocs:
"Related Pages" > ["Deprecated List"](http://www.fluidsynth.org/api/deprecated.html)

> Doesn't this go against conventions of 0 being "false"?

Yes, that's why I said they don't return bools. It's the unix convention we have here, i.e. 0 meaning success and a negative value an error.

> I don't know how to edit the wiki, unfortunately.

This isn't the wiki, it's the dev doc or API doc, which is generated from source.

**Comment by derselbst** [comment]
I had a look into this again. It seems the tuning API has been designed to satisfy the requirements of the MIDI Tuning Standard (MTS). My knowledge on this topic is very limited, never used this myself and given the fact that SF2 provides accurate tunings of instruments I cant think of any use case for this. Thus I'm not willing to mess around in that part of fluidsynth, sry.

Your best option might be to bring a discussion on this up on the mailing list. Else I'll be closing this someday.
