### ISSUE TITLE
Volume levels are different in fast-render mode

### ISSUE THREAD

**Issue by mqnc** [FluidSynth/fluidsynth#219]
I guess this should be more of a forum entry but I'm not aware of a forum...

I composed a midi file using MusE. MusE is connected to a custom python midi filter where I mix and apply effects, then it is sent to fluidsynth. This is for live composing.
Then, when I'm done, I export a midi file, run it through the same python midi filter (and store the result in a new, temporary midi file) and then render it to wav using fast-render mode in fluidsynth.
The volume levels in the resulting wav file are completely different from how I mixed it while composing.

Of course my first guess was that the problem lies in MusE or my custom filter. But I have also opened the already-filtered, temporary midi file in MusE and sent it to fluidsynth directly, it still sounds the way I mixed it. And I also monitored what MusE sends to fluidsynth and it's identical to the temporary midi file.

I'm not using channel volume or expression, mixing is done through individual note velocity which is set by the filter. The only difference is that I use Qsynth (gain 100) for live composing and a bash command for fast-rendering with -g 0.5.

I'm still not convinced the issue lies in fluidsynth but I'm running out of debugging ideas. Any remarks appreciated!

**Comment by derselbst** [comment]
Which version of fluidsynth are you using?

> And I also monitored what MusE sends to fluidsynth and it's identical to the temporary midi file.

Anyway, please open the "already-filtered, temporary midi file" in some other midi app like qtractor or rosegarden and send it to fluidsynth. To really be sure it's not a Muse issue (e.g. Muse initializing the volume or expression MIDI CC differently than the fast render does).

Consider using a different soundfont.

Perhaps also consider not using qsynth but start fluidsynth from cmd line directly

```
fluidsynth -g 0.5 someSoundfont.sf2
```

In case the problem persists, pls provide a minimal midi example file in order to better reproduce this issue.

**Comment by mqnc** [comment]
I was creating a minimal example and during the last few steps I noticed that I have reverb and chorus off in live mode but forgot to specify that for fast rendering. It made the synthesizer way louder than all other instruments, maybe hit some resonance or something.

Damn you, derselbst and your perfect program! You win once again! But I will find a bug, rest assured ;)
Thanks for your crazy fast support tho.

**Comment by derselbst** [comment]
Yeah fortunately David, Element and Pedro left a pretty stable code base. But sure, keep searching ;)

You're welcome.
