### ISSUE TITLE
midi.jack.id is ignored

### ISSUE THREAD

**Issue by mqnc** [FluidSynth/fluidsynth#224]

**Comment by mqnc** [comment]
The Jack Midi port name is also determined by the value of audio.jack.id instead

**Comment by derselbst** [comment]
`midi.jack.id` applies for jacks midi driver. if jack is used as audio driver, it's determined by `audio.jack.id`

**Comment by mqnc** [comment]
I thought that midi.jack.id is the name of the client that appears under the "MIDI" tab in QjackCtl that I can send midi messages to and audio.jack.id is the name of the client that appears under the "Audio" tab in QjackCtl where the rendered sound is put out. But both port names are determined by audio.jack.id and that's intended?

**Comment by derselbst** [comment]
> I thought that midi.jack.id is the name of the client that appears under the "MIDI" tab in QjackCtl that I can send midi messages to and audio.jack.id is the name of the client that appears under the "Audio" tab in QjackCtl where the rendered sound is put out.

Yes, that's what I wanted to say after a quick look at the code.

> But both port names are determined by audio.jack.id and that's intended?

No. Need to look into that.

**Comment by derselbst** [comment]
It's a feature. Because jacks audio server and jacks midi server are the same (i.e. `midi.jack.server` and `audio.jack.server` are equal) that jack client that was created earlier is reused (in this case, the audio client is reused). Each jack client can only have one name.

You'll have to assign different audio and midi server names. This however is tricky, because the first jack server will uniquely take ownership of your audio card, so the second server cannot be created and it fails (at least for me as it seems).

Will update the doc on [audio|midi].jack.id and close this as wontfix.

**Comment by mqnc** [comment]
I don't really mind, I just wanted to nit-pick :)
