### ISSUE TITLE
Fluidsynth always crashing on Windows

### ISSUE THREAD

**Issue by carlo-bramini** [FluidSynth/fluidsynth#259]
I synced my source tree with the latest changes in the repository, but after that my Fluidsynth brutally crashed every time I launched it.
After an hour of debugging and regression tests, I think I have found the cause.
The cause of all my troubles seems to be into src/utils/fluid_settings.c and after the change "avoid accessing uninited memory":

https://github.com/FluidSynth/fluidsynth/commit/36d8f9558448e16765198b0bdce894085949dc1c

But Fluidsynth crashed because two other bugs:

1) after adding that "num--;" in this commit, the test in this line:
https://github.com/FluidSynth/fluidsynth/blob/master/src/utils/fluid_settings.c#L425
fails and so it tries to do FLUID_LOG() message. But while the format string has a "%s" inside, you pass name[n] as parameter. name[n] is a character, not a pointer, so it crashed inside the printf() because it was an invalid address. Perhaps, you wanted to write token[n] instead.

2) After fixing (1), it also crashed into delete_fluid_ringbuffer().
This function was called by delete_fluid_rvoice_eventhandler().
And delete_fluid_rvoice_eventhandler() was called by new_fluid_rvoice_eventhandler().
Inside new_fluid_rvoice_eventhandler(), new_fluid_ringbuffer() returned NULL because the above commit, so it jumped to "error_recovery" label. But since handler->queue is NULL at this stage, the access to queue->array inside delete_fluid_ringbuffer() causes a segmentation fault.
After doing "if (queue != NULL) {" before the two free(), this crash has been also fixed.

However, although these two bugs were fixed, Fluidsynth still did not work.
This is what it is printed on the console:

> fluidsynth: warning: 'synth.overflow.percussion' is not a node
> fluidsynth: warning: 'synth.overflow.sustained' is not a node
> fluidsynth: warning: 'synth.overflow.released' is not a node
> fluidsynth: warning: 'synth.overflow.age' is not a node
> fluidsynth: warning: 'synth.overflow.volume' is not a node
> fluidsynth: warning: Requested number of audio channels is smaller than 1. Changing this setting to 1.
> fluidsynth: warning: Requested number of audio groups is smaller than 1. Changing this setting to 1.
> fluidsynth: warning: Invalid number of effects channels (0).Setting effects channels to 2.

I do not know eactly what you wanted to do with this change, but after reverting the commit, everything started to work again and normally.

EDIT: Perhaps, the cause is the "-1" applied to fluid_settings_tokenize() into fluid_settings_set(). This function returns a value from zero to "n", the later if() statement that returns FLUID_FAILED will never work in this way. In other words, I do not know if it is correct, but "num" is decreased 2 times into fluid_settings_set().

**Comment by derselbst** [comment]
Ok so, step by step: The problem prior to 36d8f9558448e16765198b0bdce894085949dc1c was that `fluid_settings_tokenize()` could return 0. It was immediately decreased by 1 yielding `num==-1`. The if clause only checks for `==0`, execution continues after the loop and uninitialized mem will be accessed at `dupname = FLUID_STRDUP (tokens[num]);`.

When looking at 36d8f9558448e16765198b0bdce894085949dc1c again, I dont really side some bad side effects that could happen. The only change is that now if `fluid_settings_tokenize()` returns one token, this will be processed, whereas before it would have been rejected.

So you only launched the fluidsynth exec and it crashed immediately? Doesnt happen on Linux. Could you post the output of cmake?

Regarding 1) you're right, %s for a char cant work. And that check only fails for the `synth.overflow.*` settings? Shouldnt even get there since num gets decremented. (BTW: pls post permalinks rather than links to files on the `master` branch, else if this file changes one doesnt see the buggy file)

Regarding 2) this seems to be a different bug in `delete_fluid_ringbuffer()`.
> new_fluid_ringbuffer() returned NULL because the above commit, so it jumped to "error_recovery" label.

Perhaps due to a zero size malloc? Still dont see how 36d8f9558448e16765198b0bdce894085949dc1c could cause this...

**Comment by derselbst** [comment]
Just pushed two fixes. Also the error msg. is now more meaning full. Could you please try again and post the output?

**Comment by carlo-bramini** [comment]
Fixed.
The cause of the issue was an inexplicable thing happened when I did the sync... there was "-1" after fluid_settings_tokenize() AND "num--" after the if() statement. My fault.
Error raised in point (1) looks fixed.
Error in point (2) happened if, for some reasons, fluid_settings_set() returned FLUID_FAILED. Now both troubles seem to be corrected. Thank you!

**Comment by derselbst** [comment]
Ok.
