### ISSUE TITLE
remove fluid_cmd_handler_register() from API

### ISSUE THREAD

**Issue by derselbst** [FluidSynth/fluidsynth#325]
I would vote for removing `fluid_cmd_handler_register()` from public API. I dont think it's useful. A user either works with fluidsynths shell or with its API. I cant think of a use-case, where a user (developer) would use this function to register custom commands to do custom things via the shell that he could probably have handled much more efficiently directly via the API.

As a consequence we could also remove `fluid_cmd_handler_unregister()`, `struct fluid_cmd_t` and `fluid_cmd_func_t` from the API.

@mawe42 @jjceresa Any thoughts?

**Comment by mawe42** [comment]
Well, I could construct a use-case... Somebody could embed fluidsynth and make use of the built in shell. He also wants to add a custom command, but doesn't want to edit the source to do that, because it would mean he would have to publish his changes under LGPL.

But that seems (and is) very constructed. :-)

I'm all for removing those internals from the public API. But maybe it would be a good idea to ask on the mailing list first?

**Comment by jjceresa** [comment]
As far i understand the set APIs  `(new_fluid_shell() , new_fluid_cmd_handler(), fluid_cmd_handler_register())` is a mean for any application developer to give to the end user of the application (not the developer)  interactive customs functionalities using a simple `console`.
If we assume that PUBLIC API `fluid_cmd_handler_register()` is no useful that means that  `new_fluid_cmd_handler()` should be not PUBLIC API also. So, if the developer cannot give to the end user a console with custom commands he will be forced to use another interactive way (GUI or whatever). 

The power of a simple console is interesting when using the TCP server. With v 1.1.6 it was possible to give to the remote end user custom commands, but now (v1.1.9) i don't think it is still possible. 

So the question that appears to me is: does it useful to give to the application end user custom interactivity through a console ?. Because of the simplicity of the console i feel favorable to keep this APIs PUBLIC and i think as mawe42  it worth to ask on the mailing list.

**Comment by derselbst** [comment]
> I'm all for removing those internals from the public API.

Yes, that's the point. `struct fluid_cmd_t` is public and needs to be made private, introducing a bunch of new getter and setter functions for a datatype that eventually no one will be using. Not even fluidsynth is using this struct internally anymore, meanwhile we have our own [lightweight struct](https://github.com/FluidSynth/fluidsynth/blob/bf5dbc60cf1e2f0fbd566fdd9fb0c22a3cd7fea8/src/bindings/fluid_cmd.c#L72)

> If we assume that PUBLIC API fluid_cmd_handler_register() is no useful that means that new_fluid_cmd_handler() should be not PUBLIC API also.

I would not go that far. The `cmd_handler` could still be useful to process a command string with `fluid_command()` or a file containing commands with `fluid_source()`. Also the `cmd_handler` is needed when creating a shell.

But sure, let's ask the mailing list.

> With v 1.1.6 it was possible to give to the remote end user custom commands, but now (v1.1.9) i don't think it is still possible.

Why do you think so? The API wasnt changed for 1.1.x. These discussions are only related to the API cleanup for fluidsynth 2.0.

**Comment by jjceresa** [comment]
>Why do you think so? The API wasnt changed for 1.1.x.
These discussions are only related to the API cleanup for fluidsynth 2.0.
 
Sorry, i was confused with the `actual master API `[calling the server](https://github.com/FluidSynth/fluidsynth/blob/980608754392095ab262fe1ae673d5f3e1e3116c/src/fluidsynth.c#L698). Please ignore this remark.

**Comment by jjceresa** [comment]
>I cant think of a use-case, where a user (developer) would use this function to register custom commands to do custom things via the shell.

Finally, looking for  `fluid_cmd_handler_register()` signature 
`fluid_cmd_handler_t* new_fluid_cmd_handler(fluid_synth_t* synth, fluid_midi_router_t* router)`,
It seems that from an application, registering custom commands to this new `command handler` isn't useful if the `custom commands procedure` cant receive a custom pointer on application `private data`.

So, i must correct my previous comments as the set APIs `(new_fluid_shell() , new_fluid_cmd_handler(), fluid_cmd_handler_register())` appears only to be specific for fluidsynth internal objects `(i.e synth,router,..) `and can't be used for custom application commands. So actually , apart @mawe42 observations i cant see a viable use of `new_fluid_cmd_handler()` been public.
So imo, it worth to do the adequate cleanup as actually if these API remains public it tends to indicate that the function is useful which is unfortunately not the case.

**Comment by derselbst** [comment]
I think the custom `void* data` you are looking for is hidden in `fluid_cmd_t` itself and always passed to the `handler` function: http://www.fluidsynth.org/api/structfluid__cmd__t.html

So while I do think custom command registering would work fine in theory, I see no practical use for it. In fact I think that every function of `shell.h` (except the `fluid_server` stuff) is redundant as it's too fluidsynth specific. The only reason they are part of the public API is because they are used in `fluidsynth.c`, which links against `libfluidsynth`. And because any function of `libfluidsynth` not marked `FLUIDSYNTH_API` is private and not exported, these `fluid_cmd_handler`, `fluid_shell` etc. functions are exposed to avoid undefined references during linking.
