### ISSUE TITLE
[PATCH] Force enable/disable OSS support

### ISSUE THREAD

**Issue by Ne01eX** [FluidSynth/fluidsynth#348]
Hi2all! This patch allow you to force enable/disable OSS support.

[fluidsynth-1.1.9-cmake_oss_fix-rtklinux-1.patch.gz](https://github.com/FluidSynth/fluidsynth/files/1793110/fluidsynth-1.1.9-cmake_oss_fix-rtklinux-1.patch.gz)

**Comment by derselbst** [comment]
Basically a good idea. However this would disable OSS support by default, because you did not introduce `enable-oss` as an `option()`.

Also it would have been nice if you had used `git format-patch` or opened a pull request as pointed out in our [CONTRIBUTING.md](https://github.com/FluidSynth/fluidsynth/blob/master/CONTRIBUTING.md#contributing).

**Comment by Ne01eX** [comment]
Done. :-) Pull request created. This issue closed. :-)
