### ISSUE TITLE
fluid_player_get_total_ticks always returns zero

### ISSUE THREAD

**Issue by rpvelloso** [FluidSynth/fluidsynth#418]
fluid_player_get_total_ticks(player) only returns zero. I was thinking about using it to compute total length of sound. How can I do this? Is there another way?

**Comment by derselbst** [comment]
fluid_player_get_total_ticks() returns the ticks of the song currently
loaded, i.e. playing. Thus you must have called fluid_player_play() and
someone (an audio driver or yourself) must be rendering audio from the
synth. This is due to the fact that the player is lacking a proper playlist
interface. It really was only built satisfy the purpose of the command line
player. If you want more functionality I suggest you use a proper midi
parsing library.

**Comment by rpvelloso** [comment]
That's what I'm doing:

`
fluid_settings_t * settings = new_fluid_settings();
fluid_synth_t * synth = new_fluid_synth(settings);
fluid_player_t * player = new_fluid_player(synth);
fluid_player_add_mem(player, fileBuffer, fileSize);
fluid_player_play(player);
std::cout << fluid_player_get_total_ticks(player) << " " << fluid_player_get_bpm(player) << std::endl;
`
It outputs: 0 125

The functionality I actualy need is: given a sequence of MIDI events (or a MIDI file for that matter) I need to know the sequence's total duration in seconds (or whatever time measure is available). Does FluidSynth has this funcionality? If not, is it too difficult to implement it? I think I could do it with a little guidance.

IMHO this kind of functionality is general enough to justify it's implementation, but I'm no MIDI expert.

**Comment by rpvelloso** [comment]
I've called fluid_synth_write_s16 before calling fluid_player_get_total_ticks and now it works. It returned 197279 ticks. How can I convert this to seconds?

**Comment by derselbst** [comment]
> Well, found that 'total_ticks * player->deltatime = duration in miliseconds'.

I'm afraid this only works if the midi file has no tempo changes. I recall my suggestion to use a proper parsing library.

**Comment by rpvelloso** [comment]
Will do, thanks for the advice.
