### ISSUE TITLE
FluidSynth and Emscripten

### ISSUE THREAD

**Issue by mmontag** [FluidSynth/fluidsynth#424]
HI, 

I've been trying to compile FluidSynth with Emscripten. Unfortunately, I didn't make it far. The problem is that FluidSynth depends on glib, which depends on other stuff that's hard to compile to LLVM bitcode.

- fluidsynth ❌ 
  - glib ❌ 
    - zlib ✅ 
    - libffti
    - ...?

I compiled zlib, but then gave up on libffti.
Difficulty is mentioned a few other places, like here https://groups.google.com/forum/#!topic/emscripten-discuss/6HMNv35m-Og.

For now, I'm building a fork of FluidSynth 1.0.9, just before the glib dependency was added, and it works. 

I wonder if anyone else has explored emscripten with FluidSynth (and has a higher tolerance for Autotools) or how difficult it would be to remove glib.

**Comment by derselbst** [comment]
> I wonder if anyone else has explored emscripten with FluidSynth (and has a higher tolerance for Autotools) or how difficult it would be to remove glib.

Please, study the following threads and learn about

1. why we are using glib
http://lists.nongnu.org/archive/html/fluid-dev/2009-08/msg00024.html
http://lists.nongnu.org/archive/html/fluid-dev/2016-01/msg00015.html

2. what needs to be done to get rid of it
http://lists.nongnu.org/archive/html/fluid-dev/2017-10/msg00045.html
http://lists.nongnu.org/archive/html/fluid-dev/2017-09/msg00031.html

3. why glib currently is the only way to go.
http://lists.nongnu.org/archive/html/fluid-dev/2017-10/msg00024.html
http://lists.nongnu.org/archive/html/fluid-dev/2017-10/msg00027.html

Also understand that this is no support forum, which is why I'm closing this. If you need help, reach out to our mailing list.
