### ISSUE TITLE
Suspected buffer overrun in soundfont loader

### ISSUE THREAD

**Issue by derselbst** [FluidSynth/fluidsynth#431]
### FluidSynth version 
2.0.0

### Current behavior
Starting fluidsynth with the jack audio driver while loading a sf3 results in a segfault. Also reproducible with a sf2 and dynamic-sample-loading activated.

### Steps to reproduce
`fluidsynth FluidR3Mono_GM.sf3  -a jack -m jack  -l`

### Other information

git bisect says a985c68a13e35120f56c3bc0854f26d43a4242b8 is to blame.

gdb output:
```
Thread 3 "fluidsynth" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffe6a06700 (LWP 19411)]
0x00007ffff5da4222 in Jack::JackLinuxFutex::Connect (this=0x855050, name=name@entry=0x7fffe6a05b54 "system", server_name=server_name@entry=0xa44a40 "default") at ../linux/JackLinuxFutex.cpp:192
192         if (! fPrivate && fFutex->wasInternal)
(gdb) print fFutex
$1 = (Jack::JackLinuxFutex::FutexData *) 0xffffffffffffffff
```

**Comment by derselbst** [comment]
Nevermind, that's a bug in jackd: jackaudio/jack2@cc8576a

**Comment by mawe42** [comment]
Well spotted, thanks! And it seems like the reason why the dynamic-sample-loading triggers this bug is because we allocate smaller chunks of memory. When a sample is below the default memlock limit, that lock succeeds in Fluidsynth but leaves jack with no more room for it's first (and apparently fairly small) locks.

When starting fluidsynth with `synth.lock-memory=0`, the crash disappears. This also explains the behaviour in #416 .
