### ISSUE TITLE
Bogus warning when loading soundfont from memory: Unable to read modificaton time of soundfont file

### ISSUE THREAD

**Issue by realnc** [FluidSynth/fluidsynth#483]
FluidSynth 2.0.2

When using a fluid_synth_t with a soundfont loaded from memory (see http://www.fluidsynth.org/api/fluidsynth_sfload_mem_8c-example.html), this is printed to stderr:

`fluidsynth: warning: Unable to read modificaton time of soundfont file.`

Fluidsynth does not have a way to distinguish between loading a soundfont from a file and loading one from memory. Perhaps it would have been better to have a different function for loading soundfonts from memory rather than using `fluid_synth_sfload()` for both? This would either allow fluidsynth to internally mark the soundfont as being in memory, or the new function could define a new callback function for this purpose (`fluid_sfloader_callback_stat_t()`). Or a callback that returns a `FILE*` handle, which is `NULL` if there's no file handle associated with the soundfont.

For now, I tried to kludge away the warning by making the filename string appear to be empty:

```
char bogus_filename[64];
bogus_filename[0] = 0;
sprintf(bogus_filename + 1, "%p", ptr);
fluid_synth_sfload(synth, bogus_filename, 1);
```

but fluidsynth still tries to do file access on it and prints the warning. Perhaps it would be better if fluidsynth would not attempt any file access and don't print a warning about it if the string appears to be empty.

**Comment by mawe42** [comment]
The warning message comes from the sample cache. Maybe we need a way to tell the loader to bypass the sample cache entirely... it probably doesn't make much sense to cache samples of soundfont that were being loaded from memory.

Otherwise setting the filename to an empty string could lead to possible false hits in the cache. The cache key consists of the filename, the modification time and the positions and sizes of the sample data chunks. If mtime and filename are always equal, then fluidsynth might load the wrong samples if they come from soundfonts with identical sample data chunk sizes and positions. Granted, that's not very likely, but definitely possible.

**Comment by derselbst** [comment]
> Perhaps it would have been better to have a different function for loading soundfonts from memory rather than using fluid_synth_sfload() for both?

This feature has been designed to avoid such a need of a distinction from where the soundfont is loaded, allowing to keep things simple. I'm still convinced that this decision was correct.

> Maybe we need a way to tell the loader to bypass the sample cache entirely... it probably doesn't make much sense to cache samples of soundfont that were being loaded from memory.

A valid point though. I see two options:

1. Check whether the filename is a soundfont file at all (`fluid_is_soundfont()`), or
1. Check whether the `fluid_file_callbacks_t` has been modified to point to custom callback functions.

**Comment by derselbst** [comment]
> So if the in-memory soundfont has a filename that (by accident) also exists in the filesystem, we still have the same behaviour.

No. In this case the soundfont loader installed in the synth by default would read it from the filesystem. The second sfloader, installed by the user to load from memory, would not see it and we could be sure that the file was loaded, not some memory.

> IMO, a new function taking a void* is clearer and simpler.

IIRC there was a problem with this method that would have led to a duplicate implementation of the current sfloader. Not quite sure.

**Comment by realnc** [comment]
> No. In this case the soundfont loader installed in the synth by default would read it from the filesystem. The second sfloader, installed by the user to load from memory, would not see it and we could be sure that the file was loaded, not some memory.

So basically the reverse of the current behavior? (Currently, if the custom sfloader's open_t callback returns NULL, fluidsynth tries to open the soundfont using the default handler.)

**Comment by derselbst** [comment]
Oh, indeed. I was convinced the default loader would be first.

Anyway, I think checking for real files is fine when deciding whether to use the cache or not. After all this is what the cache is meant to do. Letting in-memory soundfonts use the same filename as real files is what I would consider to be broken-by-design. We haven't documented the calling order of soundfont loaders (AFAIK), which would allow us to reorder them (which I'm currently not intending though). And if we did the application is uncertain whether the default or custom loader loaded that "in-memory" soundfont.

**Comment by mawe42** [comment]
> Letting in-memory soundfonts use the same filename as real files is what I would consider to be broken-by-design.

Yes, but it's broken by design through our example code. Maybe we should at least change it to use ```0``` as pointer prefix instead of ```&```. That way we can do what @realnc suggested: check for an empty filename before all default implementations of file operations. And skip the cache on an empty filename as well. And skip the fallback to the default loader altogether.

**Comment by realnc** [comment]
> Yes, but it's broken by design through our example code. Maybe we should at least change it to use `0` as pointer prefix instead of `&`.

I occurred to me that this is dangerous. There's no way to know if the string is actually empty or not. So if it's really empty, it will result in an out of bounds access in the custom sfloader. This makes using the API even more error prone than it already is.

**Comment by mawe42** [comment]
> It occurred to me that this is dangerous. There's no way to know if the string is actually empty or not.

Good point.

This whole "storing a pointer in a string" is so hackish and really a sign that we don't want to properly support this in-memory use-case. Maybe we should clean this... one idea:
- Add a new public method ```fluid_synth_sfload_fd``` that accepts a ```void *``` instead of a string filename. This method would store the passed value where we currently store the file handle, the filename of the font would be set to an empty string.
- When the filename is empty, the ```open``` callback of a loader is never called. And all other operations that would require a filename (including the sample cache) are also skipped if the filename is empty.
- Maybe also add a third parameter to the new ```fluid_synth_sfload_fd``` to control if the ```close``` callback should be called or not. That would make loading soundfonts from existing file handles extremely easy as well.

It would require some reorganisation in the file loading path, specifically everything around ```fluid_sffile_open```, but should be doable, I think.

@derselbst I would be willing to propose a PR, if you think this could be a way forward.

**Comment by derselbst** [comment]
> When the filename is empty, the open callback of a loader is never called.

This would be problematic if the memory needs to be prepared in some way. Think of locks, reference counts, shared memory. How to cope with that?

**Comment by mawe42** [comment]
> This would be problematic if the memory needs to be prepared in some way. Think of locks, reference counts, shared memory. How to cope with that?

That's the responsibility of the caller. After all, he allocated the memory region in the first place.

**Comment by derselbst** [comment]
Reading the memory from somewhere without letting the caller know when we do so seems daring to me. I'm afraid this could be the root of some other problems.

**Comment by derselbst** [comment]
> Well, the caller knows that the memory region is being read after (or rather "when") calling fluid_synth_sfload_fd, there are no asynchronous code path involved.

Imagine the user has two memory sfloaders registered (e.g. one for SF2 and another for custom stuff), how would fluidsynth know which of those loaders to use if we didn't call `open` so the application can tell us?

> But it would require us to change the signature of the callback to accept a void*.

I'm afraid there's another ambiguity here: If two or more sfloaders are registered, how should they know whether to treat that `void*` as string or byte array? In other words: fluidsynth might call a loader by passing a byte array, while the loader interprets it as string.

**Comment by mawe42** [comment]
> Imagine the user has two memory sfloaders registered (e.g. one for SF2 and another for custom stuff), how would fluidsynth know which of those loaders to use if we didn't call open so the application can tell us?

Good point, I didn't consider the case of multiple custom loaders. Ah, and I also didn't consider the soundfont reloading code path. So having an open callback is definitely necessary.

> If two or more sfloaders are registered, how should they know whether to treat that void* as string or byte array?

Ok, how about this: The custom loading function could be renamed to ```fluid_synth_sfload_custom``` (or similar) and accepts a pointer to user-data. That user data could then be a struct that contains the information for the two loaders to decide which one should feel responsible. We would need to document that when using custom loaders, their ```open_custom``` (or similar) callback should all accept the same user-data structure.

**Comment by derselbst** [comment]
> We would need to document that when using custom loaders, their open_custom (or similar) callback should all accept the same user-data structure.

It's not quite clear to me: Are you suggesting to introduce another `open` callback for the soundfont, or to use the existing one, or use the existing one with a `void*`?

**Comment by derselbst** [comment]
Option 2. would mean that whenever `fluid_synth_sfload_user()` is called, the sample cache will be disabled, correct? Wouldn't this be equivalent to disabling the sample cache for all soundfont loaders except the default loader? Keep in mind that the sample cache currently is internal to fluidsynth and (in the context of this issue) is only used because SF2 mem loading uses the defsfont loader. The sample cache cannot be used in a user-written-custom loader.

**Comment by realnc** [comment]
> You mean if it's _not_ marked as such, correct?
Yes. Typo.

> Well, that would work for your use-case, but means that caching is disabled for all custom loaders, even for those where it would make sense to cache the sample data.

You could always copy the way SDL does it. See SDL_rwops. It's a handle that is used to access data, be it from files or memory.  Fluidsynth would then only need to support that, so there's only one implementation needed. Users can create their own handles for reading from memory (or the network, or whatever.)

For this, you'd need a new soundfont loader function (like `fluid_synth_sfload_fd()` mentioned above.) The current `fluid_synth_sfload()` function would then be a wrapper around `fluid_synth_sfload_fd()`. It creates a new handle that wraps the passed filename, and then calls `fluid_synth_sfload_fd()`, passing the handle to it. Fluidsynth then uses the handle to access the soundfont data.

That method is tried and true.

**Comment by mawe42** [comment]
> Option 2. would mean that whenever fluid_synth_sfload_user() is called, the sample cache will be disabled, correct?

No, the sample cache is only disabled for files with a ```NULL``` filename.

> Keep in mind that the sample cache currently is internal to fluidsynth and (in the context of this issue) is only used because SF2 mem loading uses the defsfont loader. 

Sure, sorry. When I say "loader" I actually mean: "default loader with custom file callbacks".

**Comment by mawe42** [comment]
> No, the sample cache is only disabled for files with a NULL filename.

Or... as what I'm proposing would mean changing the signature of ```fluid_file_callbacks_t``` anyway, maybe it would be good to also add a ```stat``` or ```mtime``` callback, as suggested by @realnc earlier. And to skip the cache if that callback returns an error.

**Comment by mawe42** [comment]
> You could always copy the way SDL does it. See SDL_rwops.

So they store the user data along with the function pointers and pass in that struct to all callbacks. Also a possible way forward, but would require much more code changes.

**Comment by derselbst** [comment]
> > Option 2. would mean that whenever fluid_synth_sfload_user() is called, the sample cache will be disabled, correct?
> 
> No, the sample cache is only disabled for files with a `NULL` filename.

I see. No guarantee (a file could still be loaded by a custom loader), but a good guess.

---

I'm torn between options 2 and 3. Given the fact that this issue isn't even a bug (just an annoying warning) does not justify an ABI/API breakage (i.e. option 2). IMO it does not really justify option 3 either.

Could it be that the real bug is fluidsynth's attempt to cache each and every sample without knowing where they are from? I tend to answer this with yes... but this makes me go with option 1. Although being "attractively challenged" (admittedly), it just works.

**Comment by mawe42** [comment]
> Could it be that the real bug is fluidsynth's attempt to cache each and every sample without knowing where they are from?

Well, yes. But the way we currently suggest/support loading from memory with the default loader is also a bug, IMHO. But you are right, it's probably best to keep things separate. And discussions about changes to the loader/file callback API are more suited for the mailing list, I think.

Ok... a much less intrusive way to get rid of the warning would be: to get rid of the warning :-) It had a proper purpose some time ago, when we didn't have a way to get the mtime on Windows platforms. But that is properly handled by glib now, so the warning isn't really necessary anymore. Instead we could use  the return value to determine whether to cache the samples or not.

**Comment by derselbst** [comment]
> a much less intrusive way to get rid of the warning would be: to get rid of the warning :-)

Yes, this should be enough for a minor 2.0.3 release. Do you want to draft a PR?

And as you said options 2 and 3 can be discussed at the mailing list later for the 2.1 release.

**Comment by mawe42** [comment]
> Yes, this should be enough for a minor 2.0.3 release. Do you want to draft a PR?

Sure. Including the change to not cache any samples if we can't retrieve the mtime?

**Comment by derselbst** [comment]
> Including the change to not cache any samples if we can't retrieve the mtime?

If your schedule is not too busy and it can be done without much effort: Yes please.

**Comment by mawe42** [comment]
Done. As written in the PR description, I think bypassing the sample cache is not such a good idea after all. At least not as long as the default loader simply copies the sample data into a new buffer. So bypassing the cache only makes sense for in-memory soundfonts, if their sampledata is being read from in-place, I think. That would probably be a great feature, but quite a lot of work and definitely worth discussing in great depth beforehand.
