### ISSUE TITLE
Qustion about imported instrument zone and preset zone

### ISSUE THREAD

**Issue by jjceresa** [FluidSynth/fluidsynth#495]
@mawe42
There is something i don't remember.
For previous version to 2.0 (ie  v1.1.6), each preset zone had a private copy of instrument zones.
But for actual version, i think that this copy doesn't exist anymore. It seems that if a two distinct preset zone (i.e pz1,pz2) make use of the same instrument , then pz1, pz1 reference the same instrument zones of this instrument in memory ?. Please is it correct ?.

Probably the change were done during "dynamic sample loading" ?.  correct ?

**Comment by mawe42** [comment]
That is correct, I submitted a pull request that eleminated this copy. Noticed that it had a considerable impact on memory consumption, especially for soundfonts with lots of different present/instrument zones (ca. 30MB for the FluidaR3_GM font). The relevant pull request is #370.

At that time only the polymono code actually relied on mutable instrument zone structs, which is why I separated that information from the rest of the instrument structure. 

Does this change now pose problems for a feature you would like to implement?
