### ISSUE TITLE
Add WASAPI support.

### ISSUE THREAD

**Issue by carlo-bramini** [FluidSynth/fluidsynth#504]
The Windows Audio Session API (WASAPI) is the successor of the DirectSound for all applications starting from Windows Vista. It is able to provide excellent realtime performance. When configured in exclusive mode, it makes the same results of kernel streaming, but without the need to program in kernel mode, since it is an user mode component.

I think it will be supported one day ;)

**Comment by jjceresa** [comment]
>The Windows Audio Session API (WASAPI) is the successor of the DirectSound for all applications starting from Windows Vista. It is able to provide excellent realtime performance.

Nice proposal. Thanks Carlo.

**Comment by carlo-bramini** [comment]
I'm having some troubles with this implementation.
The new driver tries to create the interfaces that it needs, but it can fail if it runs on a version of Windows without WASAPI support included, like XP for example.
When this happens, FluidSynth exits nicely with the message:

`Failed to create the audio driver`

and it does not try to run other included drivers that may be supported.
Actually, it seems to me that the current implementation does not allow to fall down to other drivers if this condition will happen.
Perhaps, an user can decide rewrite his code by using `fluid_audio_driver_register()` and select just one driver at time, but the current code in fluidsynth.c does not seem to be able to bypass this issue.
What do you suggest to me?

**Comment by derselbst** [comment]
> and it does not try to run other included drivers that may be supported.

The user decides which driver to start by setting `audio.driver` or `-a` flag. The user gets what he wants and if it fails fluidsynth quits. That's intended for the fluidsynth executable.

A user application is free to implement a fallback for audio drivers. E.g. based on the available options for `audio.driver`. Can't recommend messing around with `fluid_audio_driver_register()` in this case. Don't see why it's needed anyway.

> The new driver tries to create the interfaces that it needs, but it can fail if it runs on a version of Windows without WASAPI support included, like XP for example.

Perhaps not making WASAPI the default driver on windows should be fine then? If the user wants it, he may specify it explicitly.

**Comment by carlo-bramini** [comment]
Excuse me, is there a particular reason because FluidSynth must fail when the first driver found in the list cannot initialize correctly? If I can say my opinion, it won't be a bad idea to continue and try to initialize the next driver in the list, when `audio.driver` is set to `"default"`.
And what about allowing `audio.driver` to handle values like `"wasapi;directsound;waveout"`?
It is fully backward compatible with current implementation when you specify a single driver and it can eventually handle more of them if requested by the user.

**Comment by jjceresa** [comment]
>Excuse me, is there a particular reason because FluidSynth must fail when the first driver found in the list cannot initialize correctly?

Typically , the driver should be chosen by the application. Also for a given driver, the audio card should be chosen by the application using `fluid_settings_foreach_option()` iteration API.
In fact, the selected couple (driver - audio card) correspond to a particular Output jack pin. This Output must be chosen by the application' user  because only the user know the physical Output he want to work with.
An other example is when the application have multiple instance of synth (i.e s1, s2) (each with a respective instance  of audio driver). In this example, only the application'user should be able to control which Output pin is used by which synth instance.

>If I can say my opinion, it won't be a bad idea to continue and try to initialize the next driver in the list, when audio.driver is set to "default".

For the reasons described above, this behaviour should be only under application'user control (i.e never under fluidsynth library control).

**Comment by carlo-bramini** [comment]
> In fact, the selected couple (driver - audio card) correspond to a particular Output jack pin. This Output must be chosen by the application' user because only the user know the physical Output he want to work with.

I understand this, but when these variables are left to `default`, in other words, the user has selected nothing actually, it looks a nonsense to me to stop to the first driver found in the list. If the user has not configured that, probably he just wants to ear sounds from the first device able to work.
However, that's just my opinion. ;)

**Comment by carlo-bramini** [comment]
> Perhaps not making WASAPI the default driver on windows should be fine then? If the user wants it, he may specify it explicitly.

This is also another solution, perhaps not as good as having the best driver in use, but better than nothing.

**Comment by derselbst** [comment]
> Excuse me, is there a particular reason because FluidSynth must fail when the first driver found in the list cannot initialize correctly?

Let me put it that way: `new_fluid_audio_driver()` and `new_fluid_audio_driver2()` **must** fail if the audio driver cannot be created, because the user has explicitly requested it with the `settings` object and for the reasons JJC mentioned.

However, I am open to change the behaviour of the fluidsynth executable. As you already said: If the user has not set `audio.driver` or `-a` when starting fluidsynth, it might indeed be a good idea to probe available audio drivers (preferably in the order they are declared in `fluid_audio_drivers[]`, maybe not necessarily, not sure). So, in case nobody contradicts with that, you are welcome to draft a PR for that.

**Comment by mawe42** [comment]
> However, I am open to change the behaviour of the fluidsynth executable. [...] So, in case nobody contradicts with that, you are welcome to draft a PR for that.

+1 from me. I think automatic probing for a working audio driver would be a good addition for the fluidsynth executable. With regard to the order: at least on Linux I would vote for trying jack last, because it might lead to a new jack server starting if one is not running already. And those servers have a tendency to simply hang around and cause problems, at least on my systems. Go for drivers without side-effects first, like alsa or OSS.

**Comment by jjceresa** [comment]
@carlo-bramini,  Please, did you made latency compare between `WASAPI` versus `dsound` using the same device ?.
This kind of information is very useful to evaluate the efficiency of WaveRT device driver used by WASAPI.

As an example compare between `WDMKS` versus `dsound` using the same device (i.e audio card SBLive !) is:
Host API     Best latency possible (i.e without underflow)
dsound        46 ms
WDMKS      17 ms

**Comment by jjceresa** [comment]
>However, I am open to change the behaviour of the fluidsynth executable. As you already said: If the user has not set audio.driver or -a when starting fluidsynth, it might indeed be a good idea to probe available audio drivers.

It will be nicer indeed particularly for beginner user intimidated by first usage of fluidsynth.

>preferably in the order they are declared in fluid_audio_drivers[].

This seems the simpler and sufficient way.
Order precedence preference for Windows should be (dsound, waveout, WASAPI, (future WDMKS), portaudio.
This order favours host api (i.e dsound,waveout) making use of the internal OS mixer that allows multiple application (fluidsynth and others) using the same device.
Also, Windows order preference above adhere to the suggested Marcus's proposal for linux (I mean consider (alsa,oss) equivalent to (dsound, waweout) (for mutiple application mixing capabilities reasons). (i haven't checked for oss !).

Note that portaudio should be the last to avoid issues pointed by Marcus:

Look what happens when:
1) portaudio is the fluidsynth driver chosen in and 
2) jack host api is chosen in portaudio
3) jack is mapped to portaudio.

This lead in infinite and a circular path (portaudio -->jack --> portaudio --> jack .....).
I've noticed jack server hanging also on Windows.

**Comment by carlo-bramini** [comment]
> Typically , the driver should be chosen by the application. Also for a given driver, the audio card should be chosen by the application using `fluid_settings_foreach_option()` iteration API.

> However, I am open to change the behaviour of the fluidsynth executable. [...] So, in case nobody contradicts with that, you are welcome to draft a PR for that.

I tried to implement that, but sadly it seems that it cannot be done easily because `fluid_settings_foreach_option()` sorts the items alphabetically before calling the callback function.
I think that it would be also useful that the callback function could return a value rather than be declared as void, so that it could be used to stop the iteration of the items.

What do tou think about introducing a `fluid_settings_foreach_option_2()` (you can write here the name you like more) which accepts an extra parameter, perhaps called `option_flags`?
Into this new parameter, the user can configure the behaviour of the iterator.
In that case, we will have 2 flags for now, do not sort and ignore return value of the callback function.
The `fluid_settings_foreach_option()` can be simply reimplemented as a wrapper to a new function.
