### ISSUE TITLE
Request: windows libinstpatch-> artifact with libinstpatch support

### ISSUE THREAD

**Issue by MaKiPL** [FluidSynth/fluidsynth#535]
### FluidSynth version 
Latest commit- e49b5ed201ae42148f95e402c2623913e282efd3

libinstpatch (as a part of DLS support) is distributed only for Linux. There are no prebuilt binaries for Windows and current source for library is Linux friendly only. I'd like to request a change to test builts on Windows binaries to supply a support for libinstpatch so I could grab an artifact as I have no single idea how I am supposed to compile libinstpatch sources to work with build of fluidsynth for Windows AMD64.
I tried to compile it via MSYS2, but I'm getting errors such as:

```
../libinstpatch/builtin_enums.h:10:2: error: expected '=', ',', ';', 'asm' or '__attribute__' before ':' token
   10 | C:/msys64/* enumerations from "IpatchBase.h" */
      |  ^
../libinstpatch/builtin_enums.h:13:2: error: expected '=', ',', ';', 'asm' or '__attribute__' before ':' token
   13 | C:/msys64/* enumerations from "IpatchConverter.h" */
      |  ^
../libinstpatch/builtin_enums.h:22:2: error: expected '=', ',', ';', 'asm' or '__attribute__' before ':' token
   22 | C:/msys64/* enumerations from "IpatchDLS2.h" */
      |  ^
../libinstpatch/builtin_enums.h:25:2: error: expected '=', ',', ';', 'asm' or '__attribute__' before ':' token
   25 | C:/msys64/* enumerations from "IpatchDLS2Conn.h" */
      |  ^
```

also tried to install libinstpatch via MSYS2 ```pacman -S libinstpatch``` but such package is not available in sources of MSYS2 pacman.d/mirrorlist

I'd be grateful for any kind of tips

**Comment by derselbst** [comment]
Efforts for getting libinstpatch built on windows have (partly) already been made (...stupid me, haven't announced the switch to github yet, sry):

https://github.com/swami/libinstpatch

The repository is lacking CI builds ATM, but it's on the TODO list. In any case, artifacts of libinstpatch should (and will) be available from the github repository above. After this has been set up, fluidsynth's CI builds may or may not be adjusted to build against libinstpatch.

**Comment by jjceresa** [comment]
Recent efforts for getting libinstpatch built on windows have already been made on GitHub repository: https://github.com/swami/libinstpatch

Sources on this repository contains important fixes to get libinstpatch running properly on Windows.
Build process (configuration + compilation) had be changed in favor of  CMake (instead of previous auto-tools).
It means that using CMake one can choose not only a linux generator but also a MS visual studio generator for Windows or MINGW (I haven't used  this). For example,  I have used VS10 to build libinstpatch on Windows XP. Building a static library or a shared library works.
In fact building methods of libinstpatch are similar to building fluidsynth library.

>as I have no single idea how I am supposed to compile libinstpatch sources to work with build of fluidsynth for Windows AMD64.

Hope that making use of CMake (>=2.6.3) and any version of Visual Studio >= VS10 (or even MINGW) should be probably fine. Of course, one don't forget the `required` dependencies: `glib`, `gobject`, `gthread` and `libsndfile` libraries.

**Comment by jjceresa** [comment]
>Hope that making use of CMake (>=2.6.3) and any version of Visual Studio >= VS10 (or even MINGW) should be probably fine. Of course, one don't forget the required dependencies: glib, gobject, gthread and libsndfile libraries.

Assuming, one choose Visual Studio generator and build `libinstpatch` project. Then, the result can be installed running `INSTALL` project. This will install libinstpach library (.h, .lib, .dll, .pc files) in the `install directory` chosen at CMake time (via  `CMAKE_INSTALL_PREFIX` variable). 

If this `installation directory` path is the same as for fluidsynth dependencies (i.e glib libraries), it should be possible to immediately build `fluidsynth` configured in CMake for using this new `libinstpatch` library dependency.

**Comment by MaKiPL** [comment]
Thank you everyone- I managed to finally build libinstpatch.lib and create pkg-config link to this library. Yet still I'm having issues. I tried MSYS2 and Visual Studio 2019, on both situations I'm getting:
```
D:/flu/fluidsynth/src/sfloader/fluid_instpatch.c:120: undefined reference to `g_object_ref'
D:/flu/fluidsynth/src/sfloader/fluid_instpatch.c:162: undefined reference to `ipatch_sample_store_cache_get_type'
D:/flu/fluidsynth/src/sfloader/fluid_instpatch.c:162: undefined reference to `g_type_check_instance_cast'
D:/flu/fluidsynth/src/sfloader/fluid_instpatch.c:246: undefined reference to `g_object_unref'
D:/flu/fluidsynth/src/sfloader/fluid_instpatch.c:246: undefined reference to `g_object_unref'
CMakeFiles/libfluidsynth.dir/objects.a(fluid_instpatch.c.obj): In function `delete_fluid_instpatch':
D:/flu/fluidsynth/src/sfloader/fluid_instpatch.c:613: undefined reference to `g_object_unref'
D:/flu/fluidsynth/src/sfloader/fluid_instpatch.c:581: undefined reference to `g_object_ref'
D:/flu/fluidsynth/src/sfloader/fluid_instpatch.c:597: undefined reference to `g_object_unref'
D:/flu/fluidsynth/src/sfloader/fluid_instpatch.c:602: undefined reference to `g_object_unref'
CMakeFiles/libfluidsynth.dir/objects.a(fluid_instpatch.c.obj): In function `delete_fluid_instpatch_preset':
D:/flu/fluidsynth/src/sfloader/fluid_instpatch.c:266: undefined reference to `g_object_unref'
CMakeFiles/libfluidsynth.dir/objects.a(fluid_instpatch.c.obj): In function `new_fluid_instpatch':
D:/flu/fluidsynth/src/sfloader/fluid_instpatch.c:433: undefined reference to `g_type_check_instance_cast'
D:/flu/fluidsynth/src/sfloader/fluid_instpatch.c:444: undefined reference to `g_object_unref'
D:/flu/fluidsynth/src/sfloader/fluid_instpatch.c:458: undefined reference to `g_object_unref'
D:/flu/fluidsynth/src/sfloader/fluid_instpatch.c:476: undefined reference to `g_type_check_instance_cast'
CMakeFiles/libfluidsynth.dir/objects.a(fluid_instpatch.c.obj): In function `convert_dls_to_sf2_instrument':
D:/flu/fluidsynth/src/sfloader/fluid_instpatch.c:362: undefined reference to `g_type_check_instance_cast'
D:/flu/fluidsynth/src/sfloader/fluid_instpatch.c:363: undefined reference to `g_type_check_instance_cast'
D:/flu/fluidsynth/src/sfloader/fluid_instpatch.c:373: undefined reference to `g_object_unref'
D:/flu/fluidsynth/src/sfloader/fluid_instpatch.c:392: undefined reference to `ipatch_sample_store_cache_get_type'
D:/flu/fluidsynth/src/sfloader/fluid_instpatch.c:392: undefined reference to `g_type_check_instance_cast'
D:/flu/fluidsynth/src/sfloader/fluid_instpatch.c:395: undefined reference to `g_object_unref'
CMakeFiles/libfluidsynth.dir/objects.a(fluid_instpatch.c.obj): In function `new_fluid_instpatch':
D:/flu/fluidsynth/src/sfloader/fluid_instpatch.c:511: undefined reference to `g_object_unref'
D:/flu/fluidsynth/src/sfloader/fluid_instpatch.c:512: undefined reference to `g_object_unref'
D:/flu/fluidsynth/src/sfloader/fluid_instpatch.c:506: undefined reference to `ipatch_item_get_flags'
D:/flu/fluidsynth/src/sfloader/fluid_instpatch.c:524: undefined reference to `g_object_get'
CMakeFiles/libfluidsynth.dir/objects.a(fluid_instpatch.c.obj): In function `convert_dls_to_sf2_instrument':
D:/flu/fluidsynth/src/sfloader/fluid_instpatch.c:388: undefined reference to `g_object_unref'
D:/flu/fluidsynth/src/sfloader/fluid_instpatch.c:368: undefined reference to `g_object_unref'
D:/flu/fluidsynth/src/sfloader/fluid_instpatch.c:369: undefined reference to `g_object_unref'
D:/flu/fluidsynth/src/sfloader/fluid_instpatch.c:358: undefined reference to `g_object_unref'
CMakeFiles/libfluidsynth.dir/objects.a(fluid_instpatch.c.obj): In function `delete_fluid_instpatch_preset':
D:/flu/fluidsynth/src/sfloader/fluid_instpatch.c:266: undefined reference to `g_object_unref'
CMakeFiles/libfluidsynth.dir/objects.a(fluid_instpatch.c.obj):D:/flu/fluidsynth/src/sfloader/fluid_instpatch.c:437: more undefined references to `g_object_unref' follow
collect2.exe: error: ld returned 1 exit status
make[2]: *** [src/CMakeFiles/libfluidsynth.dir/build.make:155: src/libfluidsynth-2.dll] Błąd 1
make[1]: *** [CMakeFiles/Makefile2:208: src/CMakeFiles/libfluidsynth.dir/all] Błąd 2
```

it's like it tries to reference glib objects from libinstpatch.lib or I might be wrong. There were no single error while building libinstpatch so I'm kind of unsure what might be happening here.

**Comment by jjceresa** [comment]
>D:/flu/fluidsynth/src/sfloader/fluid_instpatch.c:120: undefined reference to `g_object_ref'

>t's like it tries to reference glib objects from libinstpatch.lib or I might be wrong. 

It seem you aren't wrong.
Please could you precise the tool who output this kind of message ?. (compiler or linker ?).
If it is the linker, may be are you linking with libinstpatch static library ?. Please confirm .

**Comment by derselbst** [comment]
I'm getting similar linking issues with VS2019, windows 10 x64. `g_clear_object` is trivial to fix. Need to investigate why those other two `ipatch_` functions are not found. Cannot comprehend why you are getting a bunch of `g_object_unref` undefined references though...

```
"\repos\fluidsynth\build\ALL_BUILD.vcxproj" (default target) (1) ->
"\repos\fluidsynth\build\src\fluidsynth.vcxproj" (default target) (3) ->
"\repos\fluidsynth\build\src\libfluidsynth.vcxproj" (default target) (4) ->
(Link target) ->
  fluid_instpatch.obj : error LNK2019: unresolved external symbol ipatch_item_get_flags referenced in function new_fluid_instpatch [\repos\fluidsynth\build\src\libfluidsynth.vcxproj]
  fluid_instpatch.obj : error LNK2019: unresolved external symbol ipatch_sample_store_cache_get_type referenced in function convert_dls_to_sf2_instrument [\repos\fluidsynth\build\src\libfluidsynth.vcxproj]
  fluid_instpatch.obj : error LNK2019: unresolved external symbol g_clear_object referenced in function convert_dls_to_sf2_instrument [\repos\fluidsynth\build\src\libfluidsynth.vcxproj]
  \repos\fluidsynth\build\src\Release\libfluidsynth-2.dll : fatal error LNK1120: 3 unresolved externals [\repos\fluidsynth\build\src\libfluidsynth.vcxproj]

    4 Warning(s)
    4 Error(s)

```

**Comment by jjceresa** [comment]
>luid_instpatch.obj : error LNK2019: unresolved external symbol g_clear_object referenced ....

In this case, it seems that when building `libinstpatch` a static lib  was build by VS . You can check this easly looking for `property of libinstpatch's project`. (The dialog box's property show if the project is static, or dll).  You can manually force this to `dll` by clicking to the relevant line in the property dialog box.
When libinstpatch is a static library, it does not yet contains GObject functions. In this case, later when linking  fluidsynth + static libinstpatch, it is normal that the linker complain for missing function (called by libinstpatch). To fix that, we need to add GObject library in the link process (ie link(fluidsynth + static libinstpatch library + GObject library) ).
Of course there is no issue when libinstpatch is a shared library (dll), because it contains any functions code called by libinstpatch.

**Comment by jjceresa** [comment]
>Need to investigate why those other two ipatch_ functions are not found. 

>fluid_instpatch.obj : error LNK2019: unresolved external symbol ipatch_item_get_flags referenced

`ipatch_item_get_flags()` actually exits in IpatchItem.c, but it's not actually exported by libinstpatch.def. This is my fault. To fix that we need just to remove the semi column in .def file.
Please, in libinstpatch.def replace `;ipatch_item_get_flags`  by `ipatch_item_get_flags`.

>fluid_instpatch.obj : error LNK2019: unresolved external symbol ipatch_sample_store_cache_get_type

This is more tricky to fix because actually ipatch_sample_store_cache_get_type() does no exits in libinstpatch repository. Probably this function code should be in builtin_enums.c when generated by enums target (which is impossible to do on Windows). I suggest you try to execute enums target on Linux and doing a deep search in all .c file to see if we can find this hidden function. Thanks very much.

**Comment by jjceresa** [comment]
@ derselbst only, please ignore my comment above about `unresolved external symbol g_clear_object..`. Indeed , as fluidsynth is calling GObject function we need to link with GObject library.

**Comment by jjceresa** [comment]
>fluid_instpatch.obj : error LNK2019: unresolved external symbol ipatch_item_get_flags referenced

>fluid_instpatch.obj : error LNK2019: unresolved external symbol ipatch_sample_store_cache_get_type

Now, both functions have been exported in libinstpatch.def. This is in master branch commit
https://github.com/swami/libinstpatch/commit/88c90a4f79eb5f8e245af8ea2d5e0e692f238e70
So, these 2 symbols should be resolved now.

**Comment by derselbst** [comment]
Thanks @jjceresa, this fixed it.

@MaKiPL @jjceresa Build artifacts for fluidsynth on windows with libinstpatch support are now available, pls test:

https://dev.azure.com/tommbrt/tommbrt/_build/results?buildId=190&view=results

**Comment by jjceresa** [comment]
>Build artifacts for fluidsynth on windows with libinstpatch support are now available, pls test:

Extracted  fluidsynth-WinXP-x86.zip and running fluidsynth.exe leads to `cannot start this application: missing VCRUNTIME140D.DLL` message.

Investigation with the help of "dependencies watcher" tool:
1) libinstpatch-0.dll  depends on  VCRUNTIME140D.DLL and UCRTBASED.DLL which both are absent. Looking `libinstpatch-0.dll size (977 kb)` , it seems that it is a DEBUG build type. ).

2) By substitution of this `libinstpatch-0.dll (977 kb)` by my own local `libinstpatch-0.dll (release build by VS10) (446 kb)` , fluidsynth.exe 2.0.5 starts successfully even without the following useless dlls (`concrt140.dll, msvcp140.dll, vcruntime140.dll`). This is confirmed by "dependencies watcher" tool that showed that these extra dll are never called.

Please, could you provide release builds for both (libfluidsynth-2.dll, libinstpatch-0.dll) ?, I will give a try. (Note also that in general debug build suffers of lost of performance !).

Note I haven't go further to play any dls file because I am not yet familiar with these. At a glance, as fluidsynth implement solely a SF2 engine, one should expect that behaviour should be pretty the same with DLS or SF2. I mean that playing MidiFile or playing on a MIDI keyboard should work in both case. Could anybody advice or recommend for any particular useful DLS files elsewhere ?

**Comment by derselbst** [comment]
It actually was a release build, not sure why it linked against Visual Studios debug runtime. Anyway, those runtime libs are now statically linked for libinstpatch, just like we do for fluidsynth. Have another try:

https://dev.azure.com/tommbrt/tommbrt/_build/results?buildId=199&view=results

> Could anybody advice or recommend for any particular useful DLS files elsewhere ?

There should be a `gm.dls` somewhere in C:\Windows that is used by the Media Player to play MIDIs.

**Comment by MaKiPL** [comment]
Thank you. I tested on WIN10 x64- fluidsynth.exe works out-of-box. For libfluidsynth-2.dll I had to supply some mingw64/bin DLLs like:
```
libspeex-1.dll
libFLAC-8.dll
libogg-0.dll
libvorbix-0.dll
libvorbisenc-2.dll
libpcre-1.dll
libwinpthread-1.dll
```
Interops work fine- fluid_synth_sfload(intptr, string, int) works and loads DLS correctly. Played some example music and it plays 1:1 correctly. Thank you. This issue can be closed.

**Comment by jjceresa** [comment]
Anyway, those runtime libs are now statically linked for libinstpatch, just like we do for fluidsynth. Have another try:

Fluidsynth.exe start successfully.

Just a minor detail. Why fluidsynth-XXXX-x86.zip file name ?. As there is  
fluidsynth-XXXX-x64 (for 64 bits), shouldn't be preferable to use fluidsynth-XXXX-x32.zip name instead of instead of fluidsynth-XXXX-x86.zip name ?.

**Comment by jjceresa** [comment]
>Anyway, those runtime libs are now statically linked for libinstpatch, just like we do for fluidsynth. Have another try:

Fluidsynth.exe start successfully.

Just a minor detail. Why fluidsynth-XXXX-x86.zip file name ?. As there is
fluidsynth-XXXX-x64 (for 64 bits), shouldn't be preferable to use fluidsynth-XXXX-x32.zip name instead of instead of fluidsynth-XXXX-x86.zip name ?.

**Comment by jjceresa** [comment]
>Anyway, those runtime libs are now statically linked for libinstpatch, just like we do for fluidsynth. Have another try:

Fluidsynth.exe start successfully.

Just a minor detail. Why fluidsynth-XXXX-x86.zip file name ?. As there is
fluidsynth-XXXX-x64 (for 64 bits), shouldn't be preferable to use fluidsynth-XXXX-x32.zip name instead of instead of fluidsynth-XXXX-x86.zip name ?.

**Comment by derselbst** [comment]
> Why fluidsynth-XXXX-x86.zip file name ?

[x86](https://en.wikipedia.org/wiki/X86) is the correct platform specifier for 32 bit processors. x86_64 is commonly abbreviated to x64. However, I will have to rename the artifacts again. The architecture suffix in its name should correspond to cmakes architecture switch to make building easier and avoid duplications. Maybe something like `fluidsynth-Win10-Win32` and `fluidsynth-Win10-x64`. This seems strange, I know. Need to think about it.

**Comment by jjceresa** [comment]
> Maybe something like fluidsynth-Win10-Win32 and fluidsynth-Win10-x64. 

This look clear.
Anyway, without a small readme file,  it seems difficult to guess what options have been chosen at CMake time ?. Don't know if a readme file could be easily generated and added in these zip binaries ?.

**Comment by derselbst** [comment]
> Don't know if a readme file could be easily generated and added in these zip binaries ?.

Generating that file would not be a problem. But I don't see a need for it. For the build that actually generate artifacts, there are no special flags or options involved. It only compiles fluidsynth that can be run on WinXP and newer with support for libsndfile and libinstpatch. Perhaps the fluidsynth-Win10 build is more confusing than helpful, since even the WinXP version runs fine on Win10.

**Comment by jjceresa** [comment]
>For the build that actually generate artifacts, there are no special flags or options involved.

In this case, right, no need of readme file.

>Perhaps the fluidsynth-Win10 build is more confusing than helpful

imho, this shouldn't be a problem as many Windows user know that WinXP binaries runs on newer. Even, when a WinXP user try to start a fluidsynth-Win10  binaries (or even any >= Win7 binaries) he/she got a message "this application isn't a valid Win32 application".  `fluidsynth-Win10` naming should be fine enough.
