### ISSUE TITLE
Support for Yamaha XG/XG lite MIDI

### ISSUE THREAD

**Issue by mmontag** [FluidSynth/fluidsynth#560]
### Describe the solution you'd like
Would love to see support for XG MIDI effects in FluidSynth. 
Namely, stuff like EG control (attack, decay, sustain, release) and lowpass filter 
effect cutoff/resonance. XG also has some parameterized reverb and chorus. 

Are some of these already supported in the SoundFont spec?

### Describe alternatives you've considered
Software support for playing XG MIDI files is very dim:
- The unlocked S-YXG50 VSTi, based on Yamaha's original driver. This is not useful because it's a compiled Windows 32-bit binary.
- Yamaha XG playback is supported to some extent by [BASSMIDI](http://jasonwilliams400com.startlogic.com/snor/weeds/SoundFonts/XMPlay/BASSMIDI_Driver_MIDI_Implementation_Chart.htm). This is a closed source product by Un4seen Developments.

Here is a little inspiration to show XG capabilities:
https://www.youtube.com/watch?v=_mR7DV1E4KE&t=1591s

**Comment by derselbst** [comment]
> (attack, decay, sustain, release) and lowpass filter
> effect cutoff/resonance. XG also has some parameterized reverb and chorus.
> 
> Are some of these already supported in the SoundFont spec?

All of them are implemented and usable via SF modulators.

> Here is a little inspiration to show XG capabilities:

I can't hear anything that fluidsynth wouldn't be able to do.

So, it's not clear to me what makes those "XG MIDI effects" so special that you would like them to be implemented by fluidsynth?

**Comment by mmontag** [comment]
Maybe XG is out of scope for the FluidSynth project. I'm no expert so I'll just link to the spec. http://www.jososoft.dk/yamaha/pdf/XGspec2-00e.pdf

**Comment by derselbst** [comment]
The "Tone Generation Model" of fluidsynth is SoundFont. And SoundFont says, if the user wants custom control of the synthesis process, the user has to use modulators. So, what you need to do is defining XG compatible modulators in the soundfont file(s) you want to use.

If you are looking for a more comfortable way, pls. bring this topic to the mailing list for discussion. Being a little more specific about what effects you want to behave how (e.g. by providing a demo MIDI file, a demo soundfont and a rendered audio file of how it should sound) would also be very helpful for this topic. Although I had a look into the XG spec, the only meaningful table I could find is _Attached Chart 3_.

**Comment by donarturo11** [comment]
At Polyphone you can assign Control Change messages to each modulator. You can use NRPNS too. At sf2 specification is described: NRPN MSB = 120 NRPN LSB = (number of modulator).
I modified few soundfonts. You can see it and edit with Polyphone. 
Here is link to my resources: https://drive.google.com/drive/folders/11eR7k4GamaOHVBsa4OXEslz9qpJFHuED?usp=sharing

**Comment by derselbst** [comment]
@donarturo11 Thanks for sharing this. However, it is not clear to me how you know that for instance Sound Controller 4 (attack) must be a linear bipolar modulator at preset level with an amount of 19932 ?

**Comment by donarturo11** [comment]
I experimented with it. I based at information from sf24spec - http://freepats.zenvoid.org/sf2/sfspec24.pdf . At chapter nr 8 there are very good described modulators with ranges and infos about bipolar or unipolar, linear or convex. I explored too source code of juicysfplugin: https://github.com/Birch-san/juicysfplugin . I have no skills in programming so I can't modify source code of fluidsynth at base of this code. Maybe evryone, who can C++, can write patch, make own fork at github. Because of GPL license of fluidsynth, modifying and sharing of modified source code are welcome. The best solution will be write patch to include to distros packaging systems (like Debian, Fedora) and ports systems (Gentoo has system of including own patches without modify tree ports). If somebody make patch, I'll try make proper files to install at OS (PKGBUILD, ebuild, debian/rules). 
I am only musician and I prefer make own music with free (as freedom) software and I regularly check on progresses of developing this soft. 
Not all programs sounds so perfectly but I shared for everybody to modify. Publishing modified versions are welcome. I based at existing sf2. I don't know, that I made legally with microsoftgm, because of copyright, but GeneralStandardGS is shared at free license and I sent modified version to author of this sf2 too.

**Comment by derselbst** [comment]
> I experimented with it.

I see.

I think this confirms my assumption that neither GS nor XG strictly define how to implement ADSR, FilterCutoff, and FilterQ.  It is all up to user's freedom, for which, when it comes to soundfonts, it is absolutely correct to define custom modulators for every instrument or preset in the soundfont itself. Or, like juicysfplugin, use fluidsynth's API as shortcut to define custom default modulators, which basically is the same as adding them to the soundfont.

Without a spec providing concise implementation details, I don't see how to agree on implementing any XG  support to fluidsynth.

**Comment by donarturo11** [comment]
Maybe will be possible to implement GM level 2. Most functions of GS or XG like ADSR, Resonance (Timbre; CC 71) or Brightness (CC 74) are included by MMA to GM level 2.

**Comment by derselbst** [comment]
> Maybe will be possible to implement GM level 2.

No, it won't. See the following excerpt from GM2 v1.2a:

> 
> 3.3.11 Filter Resonance (Timbre/Harmonic Intensity cc#71)
> [...] Exact behavior is left to the manufacturer's discretion.
> 
> 3.3.12 Release Time (cc#72)
> [...] Exact behavior is left to the manufacturer's discretion.
> 
> 3.3.13 Attack time (cc#73)
> [...] Exact behavior is left to the manufacturer's discretion.
> 
> 3.3.14 Brightness (cc#74)
> [...] Exact behavior is left to the manufacturer's discretion.
> 
> 3.3.15 Decay Time (cc#75)
> [...] Exact behavior is left to the manufacturer's discretion.
> 
> 3.3.16 Vibrato Rate (cc#76)
> [...] Exact behavior is left to the manufacturer's discretion.
> 
> 3.3.17 Vibrato Depth (cc#77)
> [...] Exact behavior is left to the manufacturer's discretion.
> 
> 3.3.18 Vibrato Delay (cc#78)
> [...] Exact behavior is left to the manufacturer's discretion.

**Comment by donarturo11** [comment]
Thank you. I'll read it.

**Comment by donarturo11** [comment]
I saw at specifications of GM2 and XG. Controls, which I assigned in my soundfonts are bipolar. Maybe I could improve ranges.

**Comment by donarturo11** [comment]
For MuSE users (and myself) I prepared instrument definition including NRPNs for modulators according to sf2 specification. Maybe will be for somebody useful.
[GenericSoundFont.idf.zip](https://github.com/FluidSynth/fluidsynth/files/3718234/GenericSoundFont.idf.zip)

**Comment by donarturo11** [comment]
Hi. I listened Filter resonance and Filter Cutoff at my Yamaha PSR-550 and I tried improve modified sf2. I put modified versions at google-drive.

**Comment by donarturo11** [comment]
Now I understood, why controllers being subject of this discussion won't implemented in main branch of Fluidsynth. Maybe developers don't want to restrict freedom in using these controllers. Fluidsynth is sure free (as freedom) synth and some functions probably never will be implemented (like in bassmidi). I totally agree with idea leave user a lot of freedom. If someone has skills in programming, sure cans make own fork of fluidsynth and implement some functions independent of sf2 modulators like resonance, cutoff, ADSR. I think, that will be implement some function from bassmidi (sure by reverse enginering), and leave possibility control modulators by NRPN.

I think, that I helped somebody and modified soundfonts and NRPNS for MuSE are helpful. Maybe I'll try prepare it for Rosegarden. At sent examples I showed, that implement some CC in soundfont (not in synth) is possible and easy thanks to easy soft like Polyphone.

Admin cans close this thread or users are welcome to make own modifications (like me) and send here and show us.

**Comment by mmontag** [comment]
Just want to make sure I understand. In the SoundFont world, the following effects

Filter Resonance (cc#71)
Release Time (cc#72)
Attack time (cc#73)
Brightness (cc#74)
Decay Time (cc#75)
Vibrato Rate (cc#76)
Vibrato Depth (cc#77)
Vibrato Delay (cc#78)

*are built into the Fluid Synth engine*, but they are not active unless the SoundFont author specifically hooks them up through modulators. Correct?

When authoring a SF2, can these effects be defined globally (applying to every instrument)?

@donarturo11 I would be interested if you have some SF2 with the correct mapping assigned to emulate XGlite and so on.

**Comment by derselbst** [comment]
> are built into the Fluid Synth engine, but they are not active unless the SoundFont author specifically hooks them up through modulators. Correct?

Correct.

> When authoring a SF2, can these effects be defined globally

No, unfortunately. You have to apply it to every single instrument.

**Comment by donarturo11** [comment]
> @donarturo11 I would be interested if you have some SF2 with the correct mapping assigned to emulate XGlite and so on.
@mmontag I didn't modify yet. I have access only to this bank: http://www.ronimusic.com/sf2/Yamaha_XG_Sound_Set.sf2 . Is based at syxg50, but I'm not so pleased with quality. Maybe will be good to sample soundset from my Yamaha PSR 550. If do you have xg soundbank, you can send me.

**Comment by donarturo11** [comment]
I updated banks, which I put to my drive. Testing and modifying is welcome.

**Comment by donarturo11** [comment]
If author didn't make hooks to modulators, always is possible to use NRPNs. Read http://freepats.zenvoid.org/sf2/sfspec24.pdf at chapter 8 and 9. Chapter 8 is about all modulators with number, and next is about NRPN messages. I tried and I found, that this messages are 14-bit. NRPN MSB 120 is for soundfont 2.01, and will be universal. As LSB you must to put number of modulator written at this specification.

At Roland and Yamaha soundsets you have to have a notice, that are operating with MSB and LSB, but soundfont synths have only one bank address. At net is possible to find MSB LSB calculator. I didn't experimented, but I have to see it. See the specification of XG. For GS specification is included in manual of SoundCanvasVA ( https://www.rolandcloud.com/getmedia/1b9a8e2f-da5b-4ac4-a903-60d1c6dcd648/scva-manual-e.pdf ).

**Comment by mmontag** [comment]
>If author didn't make hooks to modulators, always is possible to use NRPNs. Read http://freepats.zenvoid.org/sf2/sfspec24.pdf at chapter 8 and 9. 
Thanks for the pointers, @donarturo11 and @derselbst. I might give this a try and will share back here if I make any progress.

**Comment by donarturo11** [comment]
I would like to notify about updates at my Drive. I modified SC-55 and SC-88 soundfonts. 
A propos Yamaha XG I'm trying prepare bank. Probably full implementation of XG will be impossible because more complicated bank system. Yamaha uses MSB to define Melodic, SFX org drum, and LSB to assign melodic instruments. Soundfont normally has only 128 banks (only MSB). At Viena maximum 255 (Maybe for MSB to 2 and 128 LSBs; at fluid synth is function to toggle systems of banks).
Roland GS uses MSB and LSB, but system is easier: MSB defines soundset (1 - SC55, 2 - SC88, 3 - SC-88Pro, 4 - SC-8820). 
This problem may be solved by use several soundfonts (in synth must be implemented choosing loaded sf2 by cc#0).

**Comment by donarturo11** [comment]
I tried today, with banks at qsynth. CC#00 sure choose banks inside soundfont. To choose loaded soundfont you have to entry in CC#32={sfid}. This is  different mode of choosing banks. IMHO, it will be good implement option to users define bank choosing, to setup e.g. CC#00 = {sfid}, CC#32 = bank of soundfont. Thanks to this solution it will be possible full implementation (maybe not quite full, cause is it impossible) of GS or XG.

**Comment by donarturo11** [comment]
I read at wikipedia about GS (https://en.wikipedia.org/wiki/Roland_GS#Banks), that CC#32 chooses sound family, and CC#0 Variations.

**Comment by derselbst** [comment]
Closing this, because the XG spec is not specific enough to allow fluidsynth adding appropriate modulators by default. Thus it remains the job of the user / soundfont designer to add proper modulators to the soundfont (or to fluidsynth via `fluid_synth_add_default_mod()`).

**Comment by mmontag** [comment]
@derselbst - thanks for humoring us. I learned a lot from the thread and have wound up back here few times purely through Google search.
@donarturo11 - huge thanks for sharing your modified SoundFonts in the Google Drive. I have tested and noticed the difference with ADSR controllers immediately. Now I'm wondering how easy it would be to create a batch script to wire up controllers 71-78 for any old sf2.

**Comment by zaphod77** [comment]
This is a stupidly complicated issue.

1) to support xg, you need to support all it's sysex and NRPN. Including the ability to fake GS mode when receiving a GS reset sysex, because that's what typical XG devices do. specifically, they duplicate the instrument mapping, the sysex, and the nrpn of the TG300B, which is an actual Yamaha GS compliant synth).
2) the sw60dbxg or something will have the exact implementations and 4mb sample rom needed to actually duplicate XG.
3) just using an "xg" soundfont isn't enough. we must use one that has similar patch dynamics to an actual Yamaha device. As XG uses a lot of sysex and expects both the original instruments and filter stuff to match a genuine Yamaha synth, we can't really support XG without outright stealing the samples and reverse engineering knowledge on exactly how all sysex and NRPN actually work.
4) similarly, GS if you actually read the spec implies patch dynamics similar to a Sound Canvas without actually saying it does.  Just because it has similar banks, doesn't mean the envelopes and relative volumes are the same.

You can quibble about implementation definitions not specified, but GS _really_ means "Like a Sound Canvas" and XG means "Like a DB50XG" as far as most midis are concerned.
