### ISSUE TITLE
most trivial test build fails with "fluidsynth: error: SDL2 not initialized"

### ISSUE THREAD

**Issue by fabiangreffrath** [FluidSynth/fluidsynth#622]
Hi there,

last week I modified the fluidsynth 2.1.1-1 Debian package to build with SDL2 audio support by adding `libsdl2-dev` to its Build-Depends [1]. Since then, even the most trivial test build [2] fails at run-time with a "fluidsynth: error: SDL2 not initialized" error [3]:

```
#include <fluidsynth.h>
int main(int argc, char** argv) {
    fluid_settings_t* settings;
    fluid_synth_t* synth;
    settings = new_fluid_settings();
    //Using default settings.
    synth = new_fluid_synth(settings);
    if(!synth || !settings)
	//a null pointer?
	return 1;
    delete_fluid_synth(synth);
    delete_fluid_settings(settings);
    return 0;
}
```

So, is it true that merely building fluidsynth with SDL2 audio output support requires each user of the library to link against SDL2 and initialize this before initializing fluidsynth? Or am I missing something?

Cheers,

 - Fabian

[1] https://tracker.debian.org/news/1105567/accepted-fluidsynth-211-1-source-into-unstable/
[2] https://salsa.debian.org/multimedia-team/fluidsynth/-/blob/master/debian/tests/build
[3] https://ci.debian.net/data/autopkgtest/testing/amd64/f/fluidsynth/4424678/log.gz

**Comment by derselbst** [comment]
> So, is it true that merely building fluidsynth with SDL2 audio output support requires each user of the library to link against SDL2 and initialize this before initializing fluidsynth?

Not quite. That error message only informs you that the SDL2 audio driver will be unusable, because of a missing call to `SDL_INIT()`. Fluidsynth itself will still work. In other words, only if your trivial test program wanted to use the SDL2 audio driver, you should have inited SDL yourself. Since your program doesn't use audio drivers at all, you can ignore the message.

Just in case you find it less confusing, I'm open to change the log level of this message to "warning" and elaborate a bit.

**Comment by fabiangreffrath** [comment]
> Just in case you find it less confusing, I'm open to change the log level of this message to "warning" and elaborate a bit.

Yes, please! I guess the Debian CI tool was upset about a message containing the "Error" string being printed to stdout. If you could change this to a mere warning, this would be appreciated.

**Comment by fabiangreffrath** [comment]
Top, thanks!
