### ISSUE TITLE
“set_bpm” is not effect，when using 'OpenSLES ' on the android device。

### ISSUE THREAD

**Issue by gloddream** [FluidSynth/fluidsynth#624]
fluid_player_set_bpm(player, bpm);
it is not effect，when using 'OpenSLES ' on the android device。
it is ok, when using ‘ oboe’ on the android device。
my code：
```
...
    fluid_settings_setstr(settings, "audio.driver", "opensles");
...
player = new_fluid_player(synth);
fluid_player_add(player, midf);
    if (adriver) {
        delete_fluid_audio_driver(adriver);
    }
    adriver = new_fluid_audio_driver(settings, synth);
fluid_player_play(player);
fluid_player_set_bpm(player, bpm);
```

**Comment by derselbst** [comment]
Your code is missing any kind of error handling. E.g. if the creation of the audio driver fails, you will not notice it.

Also, there is no relation between `fluid_player_set_bpm` and the kind of audio driver in use. Just that the audio driver must have been created successfully.

Are you getting any sound at all? What is fluidsynth printing to console?

**Comment by gloddream** [comment]
thanks. @derselbst 
i will add the `try{}catch(...){}` in my code
the playing  of sound is ok，just the tempo is wrong, only the bpm of midi file .
but when using "oboe" ，the tempo of player is right

**Comment by derselbst** [comment]
Fluidsynth is written in C. There are no exceptions in C. What I meant you to do is checking for `NULL` instead.

Also, what do you mean by "the tempo is wrong"? Does it play at that tempo the MIDI file natively plays at? In this case pls. note that `fluid_player_set_bpm` will only reliably work if the MIDI file itself does not contain any tempo changes, because tempo change events of the file may override any of your previous call to `fluid_player_set_bpm`.
