### ISSUE TITLE
redundant warning sent to stderr

### ISSUE THREAD

**Issue by nirodho** [FluidSynth/fluidsynth#649]
_This issue tracker is only for bug reports and concrete feature requests.
DO NOT SUBMIT SUPPORT REQUESTS OR "HOW TO" QUESTIONS HERE!
Else it might be closed without further notice._

_If you have a question look into our wiki
( https://github.com/FluidSynth/fluidsynth/wiki )
or the developer resources
( http://www.fluidsynth.org/api/ )_

_If you still have a question, need support or want to discuss ideas, contact our mailing list:
https://lists.nongnu.org/mailman/listinfo/fluid-dev_

_Below is a form that shall help getting relevant information for bugs and feature requests together.
We strongly recommend to use it! Feel free to edit or remove inapplicable/unneeded parts._

### FluidSynth version 
2.1.1

### Current behavior

The following warning appears when I initialize fluidsynth with 'audio.driver' set to 'file':
"fluidsynth: warning: SDL2 not initialized, SDL2 audio driver won't be usable"

I'm using fluidsynth as a library to produce audio files.
I have no need for SDL2 in this application, so I obviously don't want it as a dependency.

### Expected behavior

Ideally, the warning should only appear when 'audio.driver' is set to 'sdl2',
and the driver is not initialized.

### Steps to reproduce

: uname -a
Linux 5.4.0-29-generic #33-Ubuntu SMP Wed Apr 29 14:32:27 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
: cat fluid-bug.c
#include <fluidsynth.h>
int main(int argc, char** argv) 
{
    fluid_settings_t* settings;
    fluid_synth_t* synth;
    settings = new_fluid_settings();
    synth = new_fluid_synth(settings);
    /* Do useful things here */
    delete_fluid_synth(synth);
    delete_fluid_settings(settings);
    return 0;
}
: gcc fluid-bug.c `pkg-config --cflags --libs fluidsynth`
: ./a.out
fluidsynth: warning: SDL2 not initialized, SDL2 audio driver won't be usable

### Other information

work-around:
./a.out 2>/dev/null

**Comment by derselbst** [comment]
The warning is being issued in `new_fluid_settings`, when we populate the `settings` object with available options, such as devices reported by the respective audio drivers. If SDL2 is not inited, we cannot fully populate the `settings` object and thus the warning. Moving the warning to a later point is inappropriate because SDL2 could have been inited in the meantime. Also, moving it to the place where 'audio.driver' is set to 'sdl2' is inappropriate, because this only sets a value in a hash table. There should not be additional logic involved.

So, moving the warning is not so trivial, because there is no alternative appropriate location. I would rather completely remove it. I probably will, somewhen in the future.

Consider using `fluid_set_log_function()` to adjust the log behaviour.
