### ISSUE TITLE
More orchestration options between player and synthesizer

### ISSUE THREAD

**Issue by ThunkMonkey** [FluidSynth/fluidsynth#654]
### Problem
FluidSynth's player features provide straightforward options for loading MIDI files or data. For example:
```
FLUIDSYNTH_API int fluid_player_add(fluid_player_t *player, const char *midifile);
FLUIDSYNTH_API int fluid_player_add_mem(fluid_player_t *player, const void *buffer, size_t len);
```
However, the data is not actually loaded and parsed until the first call into the synthesizer. For example:
```
FLUIDSYNTH_API int fluid_synth_write_float(fluid_synth_t *synth, int len,
        void *lout, int loff, int lincr,
        void *rout, int roff, int rincr);
```
In a real-time audio synthesis environment, it is important that this call return as quickly as possible. If the first call to this method has to load and parse midi data, it could cause delays that result in audio hitches.
### Request
It would be good to provide a way for clients to orchestrate the loading and parsing of MIDI data through the player. The idea would be to have some way to load and parse the MIDI data ahead of time or in parallel so that calls to `fluid_synth_write_float` would return as fast as possible.

The easiest option for my use case would be to have FluidSynth spawn an internal thread to load/parse MIDI data and instead of waiting, have `fluid_synth_write_float` return immediately with a failure until that operation is complete.

Another option could be to provide a new function that does not return until the data added to the player is loaded and parsed:
```
FLUIDSYNTH_API int fluid_player_prepare(fluid_player_t *player);
```
The expectation would be for clients to call this before calling `fluid_synth_write_float` if they care about performance of the latter. I'm not sure how this function would behave if you have added multiple files to the player.

**Comment by derselbst** [comment]
The whole fluid_player is a simple, straight forward implementation that has various known flaws and drawbacks. It deserves a complete rewrite (using the sequencer under the hood), rather than further tweaks of the current implementation.

However, there is a lack of motivation on my side to actually do this, because serious "real-time audio synthesis" applications would not use the fluid player. They handle event processing themselves by using the sequencer, MIDI drivers or the synth directly.

> The easiest option for my use case would be 

... does that mean you are actually having audio hitch problems?

**Comment by derselbst** [comment]
Sorry, but because of the reasons mentioned earlier, I don't think this is ever going to happen.
