### ISSUE TITLE
Cannot build anymore for Windows.

### ISSUE THREAD

**Issue by carlo-bramini** [FluidSynth/fluidsynth#679]
After some additions to the drivers for Windows, the compilation fails, at least on my PC.
Actually, for making the build process working again, I had to add `ks.h` and `ksmedia.h` in the source files that used `DEFINE_WAVEFORMATEX_GUID` macro:

https://docs.microsoft.com/en-us/windows-hardware/drivers/audio/converting-between-format-tags-and-subformat-guids

However, at the moment I could not test if the updated drivers work, sorry.

EDIT: I also would like to report that the drivers of FluidSynth do not work anymore on Windows 9x/ME and on Windows NT.

![Windows NT](https://user-images.githubusercontent.com/30959007/94799973-3dd92580-03e4-11eb-820e-c0701e5f6520.png)

**Comment by jjceresa** [comment]
>Actually, for making the build process working again, I had to add ks.h and ksmedia.h in the source files that used DEFINE_WAVEFORMATEX_GUID macro:

Hello Carlo,

Both new drivers (waveout, dsound) have been updated for multi-channels support on branch master (actually the master library version is 2.1.5). Here this have been build (using VS10) and tested successfully only on Windows XP. As, I don't have Win9x nor NT,  I cannot  test this on these OS. Thanks you for making a try.

These new drivers rely on the following simple substitution:

- 1)making use of format `WAVEFORMATEXTENSIBLE `instead of  **WAVEFORMATEX**. (This is required for audio devices channels > 2).

- 2)calling `fluid_synth_write_float_channels()`, `fluid_synth_write_s16_channels()` (added in fluid_synth.c) instead of respective **fluid_synth_write_s16()**, **fluid_synth_write_float()** (which are limited to 1 stereo output).

For point 1 the new structure WAVEFORMATEXTENSIBLE field `SubFormat `is a GUID initialized with DEFINE_WAVEFORMATEX_GUID macro which is defined in `mmreg.h` (when using VS 10) (so there no need to include  ks.h and ksmedia.h). 
At execution, using `waveout`, If  the format WAVEFORMATEXTENSIBLE  isn't not accepted by Windows 9x/ME or Windows NT, the driver will fail when opened (waveOutOpen(), line 424) ,and the message  "Failed to open waveOut device" should be printed on stdout. Please make a try!

>EDIT: I also would like to report that the drivers of FluidSynth do not work anymore on Windows 9x/ME and on Windows NT.

Please make use of master fluidsynth 2.1.5 library instead of 2.0.0. Using waveout you should got  "Failed to open waveOut device" in the case of driver failure. I will stay tuned.

**Comment by carlo-bramini** [comment]
> Please make use of master fluidsynth 2.1.5 library instead of 2.0.0. Using waveout you should got "Failed to open waveOut device" in the case of driver failure. I will stay tuned.

I'm already using version 2.1.5. The screenshot says "2.0.0" just because I have not updated the numbers inside the config.h into my MSVC project tree.

**Comment by derselbst** [comment]
@carlo-bramini I've improved the error reporting for Waveout and dsound drivers. There should be a meaningful error message this time, please try again.

> I had to add ks.h and ksmedia.h

Why is `ks.h` needed? According to the docs `ksmedia.h` should be sufficient.

**Comment by derselbst** [comment]
And please make sure to enable the `FLUID_LOG` macro.

**Comment by carlo-bramini** [comment]
Hello,

> Why is `ks.h` needed? According to the docs `ksmedia.h` should be sufficient.

This is what you get when you use `ksmedia.h` without `ks.h`:

```
include\ksmedia.h(16) : fatal error C1189: #error :  KS.H must be included before KSMEDIA.H
Error executing cl.exe.

fluidsynth.exe - 1 error(s), 0 warning(s)

```

**Comment by derselbst** [comment]
Ok thanks. I've added the includes. Pls. try again.

**Comment by jjceresa** [comment]
>However, at the moment I could not test if the updated drivers work, sorry.

For **primary** tests you need only an audio device with **one stereo output** (the one you already have). These **primary** tests could be done with usual default settings (synth.audio-groups = 1, synth.audio-channels = 1 or respective shortcut "-G 1  -L 1")
- 1.1: waveout - Win9X , 1.2: dsound Win9X.
- 2.1: waveout - NT , 2.2, dsound - NT.
If those important tests succeed, that means that new fluid drivers work on Win9X/NT. If you already done these easy primary test, please let us know.

Later you could do further tests with more that one stereo output, but of course this require an audio device with more than one stereo output. For example using an audio device with 3 stereo outputs, you need to set the following options in command line "-G 3  -L 3" which is equivalent to synth.audio-groups = 3, synth.audio-channels = 3. If your audio device is less than 3 stereo outputs, the driver creation will fail.

**Comment by jjceresa** [comment]
@carlo-bramini, using PR https://github.com/FluidSynth/fluidsynth/pull/687  the drivers should work as before on any Windows versions.

**Comment by derselbst** [comment]
@carlo-bramini Can you pls test recent master?

**Comment by carlo-bramini** [comment]
> 
> 
> @carlo-bramini Can you pls test recent master?

It seems to work fine on Windows 98.
I could not test it on Windows NT at the moment, but I will do it.
