### ISSUE TITLE
fluidsynth export single midi channel to wav

### ISSUE THREAD

**Issue by ryzhak** [FluidSynth/fluidsynth#695]
Hi!

I'm very new to the music tech so bear with me. 

There 16 channels in a midi file. I'm trying to convert only 1 channel from a midi file to wav.

Here is how it works now:
```
extern "C" JNIEXPORT void JNICALL Java_com_test_MainActivity_convertMidiToWav(JNIEnv* env, jobject, jstring jSoundfontPath, jstring jOutputWavPath, jstring jMidiPath, jint jChannel) {
    fluid_settings_t* settings;
    fluid_synth_t* synth;
    fluid_player_t* player;
    fluid_file_renderer_t* renderer;

    settings = new_fluid_settings();

    // specify the file to store the audio to
    const char* outputWavPath = env->GetStringUTFChars(jOutputWavPath, nullptr);
    fluid_settings_setstr(settings, "audio.file.name", outputWavPath);

    // since this is a non-realtime scenario, there is no need to pin the sample data
    fluid_settings_setint(settings, "synth.lock-memory", 0);

    synth = new_fluid_synth(settings);

    // set basic channel
    fluid_synth_reset_basic_channel(synth, -1);
    fluid_synth_set_basic_channel(synth, jChannel, FLUID_CHANNEL_MODE_OMNION_MONO, 1);

    // Load sample soundfont
    const char* soundfontPath = env->GetStringUTFChars(jSoundfontPath, nullptr);
    fluid_synth_sfload(synth, soundfontPath, 1);

    const char* midiPath = env->GetStringUTFChars(jMidiPath, nullptr);
    player = new_fluid_player(synth);
    fluid_player_add(player, midiPath);
    fluid_player_play(player);

    renderer = new_fluid_file_renderer (synth);
    while (fluid_player_get_status(player) == FLUID_PLAYER_PLAYING)
    {
        if (fluid_file_renderer_process_block(renderer) != FLUID_OK)
        {
            break;
        }
    }

    // just for sure: stop the playback explicitly and wait until finished
    fluid_player_stop(player);
    fluid_player_join(player);

    delete_fluid_file_renderer(renderer);
    delete_fluid_player(player);
    delete_fluid_synth(synth);
    delete_fluid_settings(settings);
}
``` 

Notice these 2 lines:
```
fluid_synth_reset_basic_channel(synth, -1);
fluid_synth_set_basic_channel(synth, jChannel, FLUID_CHANNEL_MODE_OMNION_MONO, 1);
```

`jChannel` is the midi channel number(1-16). I'm not really sure whether I'm doing it right.

Could somebody tell me how to convert exactly 1 midi channel to wav? Does the above code converts a single channel?

Thanks in advance

**Comment by derselbst** [comment]
Nope, you cannot wrap a question in a bug ticket. This is no support forum, use our mailing list.

**Comment by jjceresa** [comment]
>jChannel is the midi channel number(1-16). 

No, in fluidsynth API MIDI channel parameter are zero based (0 to 15).

>Notice these 2 lines: I'm not really sure whether I'm doing it right.
>(1) fluid_synth_reset_basic_channel(synth, -1);
>(2) fluid_synth_set_basic_channel(synth, jChannel, FLUID_CHANNEL_MODE_OMNION_MONO, 1);

1)The first line remove any basic channels groups. So all MIDI channels are disabled. That means that any MIDI messages received will be ignored.
2)The second line  "says" to the synthesizer that all MIDI channels (i.e OMNION) from basic channel 1 (1 to 15) should be played monophonic.This is not what you expected!. What you need is only one channel  x enabled (i.e OMINOFF) without changing the polyphonic/monophonic behaviour of this channel x. You should consider `fluid_synth_set_basic_channel(synth, jChannel, FLUID_CHANNEL_MODE_OMNIOFF_POLY, x)`.

Attention: This will work only if you are sure that the MIDIFILE currently played never change the `MIDI mode (omni on/off poly/mono)` by sending the appropriate CC messages (124d to 127d). Unfortunately most MIDIFILE usually contain  those CC.
So, to be sure of the result you must remove these 2 lines and edit the MIDIFILE by removing all track except the one that contain the instrument on the channel x. Then you could use your code that look fine.

note: GitHub  is not the correct place to solve your issue. Instead you should use the mail list `fluid-dev@nongnu.org` because there are many users that can help since many years. Of course GitHub is the correct place if you find any bug in fluidsynth.

**Comment by ryzhak** [comment]
@jjceresa thank you for the answer!

I've posted the same question at https://lists.nongnu.org/archive/html/fluid-dev/2020-10/msg00020.html

I haven't found any APIs in fluidsynth 2.1.5 for removing tracks and checking if track contains a separate instrument on the channel X. Could you show me them?

Thanks in advance

**Comment by jjceresa** [comment]
>I haven't found any APIs in fluidsynth 2.1.5 for removing tracks and checking if track contains a separate instrument on the channel X. Could you show me them?

No because there is no API to edit MIDI Files in Fluidsynth. Please ignore this solution and go directly to the mail list and read Tom's solution which is very well suited to your use case.

**Comment by ryzhak** [comment]
@jjceresa ok, thank you, I will try that solution

**Comment by ryzhak** [comment]
@derselbst Thank you, your solution at https://lists.nongnu.org/archive/html/fluid-dev/2020-10/msg00022.html seems to be working

SO answer with source code: https://stackoverflow.com/questions/64503636/how-to-export-a-single-midi-channel-to-wav-with-fluidsynth/64529886#64529886

**Comment by jjceresa** [comment]
@ryzhak  Thank you for your example answer source. But again this is not the right place to post this here because this issue is closed and your work will be quickly forgotten. Instead you should post this on the `fluid-dev` list as a `direct`  response to Tom's fluid-dev mail. This will make your `issue and solution` exposed in the same `fluid-dev place` to a lot of person.
