### ISSUE TITLE
Oboe driver can have lower latency if Oboe sample rate conversion used

### ISSUE THREAD

**Issue by philburk** [FluidSynth/fluidsynth#740]
Thanks for adding support for Oboe!

I notice that you sometimes set the sample rate explicitly.
If AudioFlinger does the sample rate conversion then it can add 80+ msec of latency.
So we added an SRC in Oboe that only adds a few msec.

To enable it:

    builder.setSampleRateConversionQuality(SampleRateConversionQuality::Medium);

Docs at:

https://google.github.io/oboe/reference/classoboe_1_1_audio_stream_builder.html#af7d24a9ec975d430732151e5ee0d1027

**Comment by Mapiarz** [comment]
@philburk Is `setFramesPerCallback` invoked in the Oboe driver relevant to latency in any way? I've tried to wrap my head around how it relates to internal buffer size and frames per burst (which when running on OpenSL ES has to be set manually via the `oboe::DefaultStreamValues::FramesPerBurst` setting).

**Comment by philburk** [comment]
Supporting setFramesPerCallback(N) requires the allocation of an extra buffer of size N. That buffer sits between the callback and the underlying API. If N and the framesPerBurst do not align then there can be data left in that buffer between callbacks. The data sitting in that buffer will add to the latency.

**Comment by Mapiarz** [comment]
Excuse my ignorance but does FS require a constant number of frames per callback? If it does not, it could (and should) be left unspecified according to the docs:
https://google.github.io/oboe/reference/classoboe_1_1_audio_stream_builder.html#afb8e95e80df7edd1af27af490438785e

If it does indeed require a constant number of frames per callback, what would be the best strategy for assuring that it matches framesPerBurst? Devices using either AAudio and OpenSL ES should be considered. For AAudio, Oboe driver could just open a stream and call `getFramesPerBurst` to get the optimal number. For OpenSL ES, I think it would be up to the user to provide the optimal number (which can be retrieved in Java: https://github.com/google/oboe/blob/master/docs/GettingStarted.md#obtaining-optimal-latency) and pass it on to FS as a fallback so that FS could set it in Oboe: https://google.github.io/oboe/reference/classoboe_1_1_default_stream_values.html.

As for sample rate, FS Oboe driver sets it explicitly so in a case where it does not match the devices native sample rate, using Oboe's SRC will be a big benefit. Nonetheless, maybe the FS Android/Oboe docs should mention that users should set `synth.sample-rate` to the output device's native sample rate for best latency? Again, it's explained how to retrieve the native sample rate here: https://github.com/google/oboe/blob/master/docs/GettingStarted.md#obtaining-optimal-latency

**Comment by derselbst** [comment]
Thanks for your recommendations @philburk ! I've already started implementing them.

@Mapiarz: FS rendering functions can be called with arbitrary number of frames. So I'll leave that unspecified.
