### ISSUE TITLE
Fix preset/instrument zone validation logic

### ISSUE THREAD

**Issue by derselbst** [FluidSynth/fluidsynth#813]
### FluidSynth version
_any_ version back to iiwusynth

### Describe the bug
This is a follow-up task to #810. It was discovered that the logic in `load_pgen()` and `load_igen()` around `*hz` is broken.

Implement a bunch of test cases that validate the current behaviour and afterwards fix the zone moving logic in both functions.

**Comment by mawe42** [comment]
As preparation I'm currently preparing a PR that simply renames some variables. I think all those `p3`, `p2` and `p` vars make the code really hard to understand and reason about.

**Comment by derselbst** [comment]
I think it's ok if we fix this after 2.2.0. For now, I would like to publish a release candidate, so that we can release 2.2.0 in early April.

**Comment by mawe42** [comment]
Yes, I think so as well. I've experimented with file format fuzzing using [AFL](https://github.com/google/AFL). Before the fix in #810, it quickly identified some crashes. With current master, it's now at > 5 million permutations and hasn't found a crash or timeout so far. I'll leave it running at bit longer, but I think at least our loader code is quite robust against broken soundfonts now.

**Comment by derselbst** [comment]
Interesting, haven't heard of AFL before.

In the meantime, I've started implementing a test on [this branch](https://github.com/FluidSynth/fluidsynth/tree/zone-validation-test). The idea is to set up a rough structure of a `SFData` (e.g. one preset, one instrument, each having some zones with some generators assigned), and then we use the file-callbacks to read from a custom buffer that contains the malformed (or correct) data.

**Comment by mawe42** [comment]
Looks good, although I wonder if it would be better to test this on a higher level. Maybe we could create some fairly simple sf2 files with and without defects, then check that the loaded structure of the file is correct. That might make the test more "future proof", and would test even more code paths at the same time.

**Comment by derselbst** [comment]
So, you vote for an integration test. This probably would be more future proof. But also harder to create. And harder to debug in case something breaks.

I had in mind to concentrate on this validation logic and create as many tests as necessary to cover any branch in two functions at least once. This will be already complicated enough. Setting up an entire SF2 file for all those cases... oh dear, I don't know.

**Comment by mawe42** [comment]
I had something like this in mind:
 - Create utility functions to turn a `fluid_defsfont_t` into a text representation, maybe best to use XML (using libxml2) or another well-defined format. So this would dump all relevant info about samples, presets, zones in presets, instruments and zones in instruments to this representation.
 - Create a small tool that takes an input SoundFont and mangles it according to some rules. The rules could be encoded in the name of the item. For example: if a preset has the string "#GZinvalid" in the name, move the global zone to a later position. Or if "#LEoutside" is in the name of a sample, move the loop end marker beyond the sample end marker. This tool could even be written in something a little more flexible, like Python.
 - Create a very small test Soundfont, with only a few presets, instruments and very short samples. Include valid data, but name some items so that they get mangled by the tool.
 - Generate representations of the desired state after loading that test soundfont and store it on disk.
 - Write a testcase that compares the desired representation against the computed representation and throw an error if there are differences. With the right representation, we could even display a diff on failure.

Yes... quite a lot of work. But in my opinion with some huge benefits, because it would test a lot(!) of previously untested code-paths, giving us a lot of confidence when making changes to the loader and defsfont code.

**Comment by mawe42** [comment]
Or another option could be to leave out the mangling tool (which would save a lot of work already). Create integration test with the XML representation only for valid soundfonts, to make sure that our loader still works for the good case. Then use AFL or another fuzzer to create small test soundfonts that crash previous versions of FluidSynth (i've got two already on disk that crash < 2.1.8). Commit those bad fonts and use those for automatic regression tests. Then create separate unit tests for the sample indices checks and the global zone moves, if required.

That would reduce the work (the mangling tool would probably take quite a while)... while still giving us a safety net for refactorings in the defsfont, loader and sffile code.

**Comment by derselbst** [comment]
I do favor with your second approach. So why don't we do both? Your approach would test the sfont loader code as a whole, which would be a good future-proof integration test.

My approach would concentrate only on the twisted zone validation logic. And having your test would probably allow to keep my test-cases at a minimum as well. What do you think?

**Comment by mawe42** [comment]
Sound good!

Do you agree that using libxml2 for creating the representation would be a good idea? Or is adding another  dependency for the tests a reason we should go for a simpler text format?

**Comment by derselbst** [comment]
Well, if you have a simple text format, that is super simple to implement and easy to use without having to add an extra dependency, that would be great. On the other hand, I wouldn't mind if we add libxml2. If it hurts anyone, we probably could convince CMake to make it optional, or so.

**Comment by mawe42** [comment]
There is a draft PR in #818 that adds the integration test.

**Comment by mawe42** [comment]
Having thought about this some more, I don't think we should "fix" the code that moves a global zone. If our analysis is correct (which I think it is), then this code hasn't been active for a very long time. That means if we were to fix the code so that the move could actually happen, we would introduce a new behaviour. And I don't think activating that new behaviour would help much. If the code detects a global zone in the wrong place, it could be due to many reasons:
 - it is really meant to be a global zone and it is simply in the wrong place
 - it is a normal zone but the SF editor somehow forgot to add the instrument generator
 - it is a normal zone but the generator(s) of the zone got corrupted somehow
 - it is a very corrupted terminal zone looking like a global zone by chance
 - and possibly many more...

Fixing the zone to be a proper global zone by moving it would only be correct in one of these cases. In all other cases, the preset would still be broken, just in a different way.

So in my opinion, we should simply add a warning message if we detect a global zone in the wrong place, then carry on loading the file.

**Comment by derselbst** [comment]
> So in my opinion, we should simply add a warning message if we detect a global zone in the wrong place, discard it and then carry on loading the file.

Yes, I agree. Also, this way it would be more consistent with the rest of our behaviour when e.g. verifying the order of generators.
