### ISSUE TITLE
Calling fluid_player_join causes an infinite loop after fluid_player_stop

### ISSUE THREAD

**Issue by rubidium42** [FluidSynth/fluidsynth#872]
### FluidSynth version
Since 676923757c4f96c5c34931da5566d5b5be3e15eb. v2.2.0.rc1 fails, v2.2.0 fails, 0ea101721aa96a504c51c8f697733a28046b35f5 fails. All compiled on Debian Bullseyes.

### Describe the bug
Calling `fluid_player_join` causes an infinite loop after `fluid_player_stop`.

### Expected behavior
That `fluid_player_join` does not cause an infinite loop in this situation. It did work in at least v2.1.8 and v2.2.0.beta1.

### Steps to reproduce
Attached is a small example program that shows the behavior. [fluidsynth_infinite_loop.zip](https://github.com/FluidSynth/fluidsynth/files/6411267/fluidsynth_infinite_loop.zip)

### Additional context
The regression is caused by #783 adding a `STOPPING` state, and in this flow that never transitions to `STOPPED` so `fluid_player_join` keeps waiting forever.

**Comment by derselbst** [comment]
Thanks for the detailed report. The problem in your provided example is that no audio rendering is happening when joining the player, i.e. no audio driver is running and no other thread calls `fluid_synth_write_*`. The transition to `FLUID_PLAYER_DONE` however can only safely be made from synth context. Looking into openTTDs source code, it seems that `fluid_synth_write_s16` is called by the same thread which is trying to join the player. And fluidsynth has no chance to detect whether a synth context is still running or not.

The only idea I have right now, is that you do not call `fluid_player_join` when you know that your rendering has stopped.

...I'll need to think about this.

**Comment by rubidium42** [comment]
Thanks for the information. Only problem we got is that some of the audio drivers have their own thread whereas others do not, making it more complicated. I'll have to see what might be possible to do safely on OpenTTD's side.

**Comment by derselbst** [comment]
I cannot think of a different solution than updating the calling conventions for `fluid_player_join()`. Technically, this function should wait until it's safe for the player to be deleted, i.e. if it's not used by the synth context anymore. This is what it does since 2.2.0. In previous versions `fluid_player_join()` wasn't of any real use, as it always returned after `fluid_player_stop()` was called.

That way, it makes no sense to join when the client knows that no synth context is running concurrently.

@mawe42 I would like to hear your opinion. If you're fine I would document this behaviour accordingly.

**Comment by mawe42** [comment]
It seems to me like `fluid_player_join()` returning does not guarantee that it is safe to delete the player, even after the changes in 2.2.0. Another thread could have started a new song after that function has returned, couldn't it?

So I guess my opinion is:
- This function has the wrong name. `_join` somehow implies that it behaves similar to a thread join. So that the player is "dead" and can be cleaned up. Which I think is not the case at all.
- The changes we introduced to `fluid_player_join()` aren't really an improvement, because this function still can't guarantee that it is safe to delete the player.

Based on that I would suggest:
- Restore the old `fluid_player_join()` behaviour and deprecate the function.
- Add a note to the documentation of `fluid_player_join()` to say something along the lines: "This function does not guarantee that the player isn't used anymore. This is up to the caller."
- Document that `fluid_player_get_status()` should be used instead. Leave status checks in infinite loops up to the caller.

But this is purely based on a quick look at the code. It might be that I have completely misunderstood the problem.

**Comment by mawe42** [comment]
And to elaborate a bit more: I think the expectation stated in #784 ("I expect to be able to delete() a player after join() has returned.") has not actually been addressed with the changes in 2.2.0. For that the function would also need to unregister the system/sample timer as well, preventing any further use of this player by the synth.

That might actually lead to a cleaner API: make `new_fluid_player()` and `delete_fluid_player()` not affect the synth in any way. Then add a `fluid_synth_register_player()` and `fluid_synth_unregister_player()` to hook the player into the synth timers and remove the timers as well. This would probably mean we need a new mutex around the timers. And it would be a major API change.

Maybe a quick fix would be to let `fluid_player_join()` break the loop on `FLUID_PLAYER_STOPPING` or `FLUID_PLAYER_DONE`. Then deprecate the function (the more I think about it, the more troublesome I consider it).

And to extend the documentation with an example for both use-cases (which I think is what you suggested, Tom):
1. Waiting for playback to have stopped with synth context still active (i.e. waiting for `FLUID_PLAYER_DONE` with `fluid_player_get_status()`)
2. How to safely delete a player (i.e. stopping all audio drivers or custom synth contexts, only then delete the player).

**Comment by derselbst** [comment]
> Another thread could have started a new song after that function has returned, couldn't it?

No, it's not a use-case to access the player from multiple threads. The player does not provide this level of thread safety.

> For that the function would also need to unregister the system/sample timer as well, preventing any further use of this player by the synth.

Technically, yes. But this is an issue that we could probably solve internally somehow. E.g. by returning 0 rather than 1:
https://github.com/FluidSynth/fluidsynth/blob/f88f27c0daf7e9898f35490b9049dbde443f14d3/src/midi/fluid_midi.c#L2091

And yes, "join" is a poor name. But I'd prefer to keep having control of how that "joining" is implemented rather than telling clients to implement their own busy wait loop and deprecate this function.

**Comment by mawe42** [comment]
> No, it's not a use-case to access the player from multiple threads. The player does not provide this level of thread safety.

Ok, then ignore that comment.

> Technically, yes. But this is an issue that we could probably solve internally somehow. E.g. by returning 0 rather than 1

Yes, that would be quite elegant. But it would still require one of the rendering functions to be called before it takes effect.

Hm... I think I'm still in favour of reverting #783. The fix for the race-condition mentioned in that issue is really just the following line:
https://github.com/FluidSynth/fluidsynth/blob/f88f27c0daf7e9898f35490b9049dbde443f14d3/src/midi/fluid_midi.c#L2159

The new `FLUID_PLAYER_STOPPING` state is used to make it safe to immediately delete the player after `fluid_player_join()` returns. And in my opinion, that is simply a wrong expectation. That's not what the function was originally meant (and documented) to do.

The documentation for `fluid_player_join()` has never announced it as being a guard after which you can safely delete the player  when there is still an audio driver active. On the contrary, the [API doc](https://www.fluidsynth.org/api/group__midi__player.html#ga9e655b26be62b17c59319a287ef382f3)  for `delete_fluid_player()` clearly states: 
> Do not call while the synth renders audio, i.e. an audio driver is running or any other synthesizer thread calls fluid_synth_process() or fluid_synth_nwrite_float() or fluid_synth_write_*() !

So in my opinion, having the possibility of endless loops in a library is way too high a cost for adding this new (and not even documented) feature of `fluid_player_join()`.

**Comment by mawe42** [comment]
> So in my opinion, having the possibility of endless loops in a library is way too high a cost for adding this new (and not even documented) feature of fluid_player_join().

Or to phrase it differently: having to document this dependency between `fluid_player_join()` and something calling a render function to avoid endless loops is not worth it. It adds an un-intuitive stumbling block into the API usage, in my opinion.
